In [1]:
import pandas as pd
import numpy as np
import datetime
import time

In [2]:
datetime.datetime(1963,7,31), datetime.datetime(2018, 6, 29, 0, 0)

(datetime.datetime(1963, 7, 31, 0, 0), datetime.datetime(2018, 6, 29, 0, 0))

In [3]:
data = pd.read_csv('div_filled.csv', low_memory=False)

In [4]:
data

         PERMNO        date    DIVAMT        PRC    SHROUT datetime date
0         10000  1985/12/31  0.000000        NaN       NaN    1985-12-31
1         10000  1986/01/31  0.000000    4.37500    3680.0    1986-01-31
2         10000  1986/02/28  0.000000    3.25000    3680.0    1986-02-28
3         10000  1986/03/31  0.000000    4.43750    3680.0    1986-03-31
4         10000  1986/04/30  0.000000    4.00000    3793.0    1986-04-30
5         10000  1986/05/30  0.000000    3.10938    3793.0    1986-05-30
6         10000  1986/06/30  0.000000    3.09375    3793.0    1986-06-30
7         10000  1986/07/31  0.000000    2.84375    3793.0    1986-07-31
8         10000  1986/08/29  0.000000    1.09375    3793.0    1986-08-29
9         10000  1986/09/30  0.000000    1.03125    3793.0    1986-09-30
10        10000  1986/10/31  0.000000    0.78125    3843.0    1986-10-31
11        10000  1986/11/28  0.000000    0.82813    3843.0    1986-11-28
12        10000  1986/12/31  0.000000    0.51563    3843.0    1986-12-31
13        10000  1987/01/30  0.000000    0.40625    3893.0    1987-01-30
14        10000  1987/02/27  0.000000    0.40625    3893.0    1987-02-27
15        10000  1987/03/31  0.000000    0.25000    3893.0    1987-03-31
16        10000  1987/04/30  0.000000    0.23438    3893.0    1987-04-30
17        10000  1987/05/29  0.000000    0.21875    3893.0    1987-05-29
18        10000  1987/06/30  0.000000        NaN    3893.0    1987-06-30
19        10001  1985/12/31  0.000000        NaN       NaN    1985-12-31
20        10001  1986/01/31  0.000000    6.12500     985.0    1986-01-31
21        10001  1986/02/28  0.000000    6.25000     985.0    1986-02-28
22        10001  1986/03/31  0.031667    6.31250     985.0    1986-03-31
23        10001  1986/04/30  0.031667    6.37500     985.0    1986-04-30
24        10001  1986/05/30  0.031667    6.31250     985.0    1986-05-30
25        10001  1986/06/30  0.035000    6.12500     985.0    1986-06-30
26        10001  1986/07/31  0.035000    6.06250     985.0    1986-07-31
27        10001  1986/08/29  0.035000    6.50000     985.0    1986-08-29
28        10001  1986/09/30  0.035000    6.37500     991.0    1986-09-30
29        10001  1986/10/31  0.035000    6.62500     991.0    1986-10-31
...         ...         ...       ...        ...       ...           ...
4098016   93436  2016/01/29  0.000000  191.20000  132056.0    2016-01-29
4098017   93436  2016/02/29  0.000000  191.92999  132056.0    2016-02-29
4098018   93436  2016/03/31  0.000000  229.77000  133858.0    2016-03-31
4098019   93436  2016/04/29  0.000000  240.75999  133945.0    2016-04-29
4098020   93436  2016/05/31  0.000000  223.23000  147543.0    2016-05-31
4098021   93436  2016/06/30  0.000000  212.28000  148015.0    2016-06-30
4098022   93436  2016/07/29  0.000000  234.78999  148693.0    2016-07-29
4098023   93436  2016/08/31  0.000000  212.00999  149239.0    2016-08-31
4098024   93436  2016/09/30  0.000000  204.03000  149825.0    2016-09-30
4098025   93436  2016/10/31  0.000000  197.73000  149891.0    2016-10-31
4098026   93436  2016/11/30  0.000000  189.39999  149964.0    2016-11-30
4098027   93436  2016/12/30  0.000000  213.69000  161561.0    2016-12-30
4098028   93436  2017/01/31  0.000000  251.92999  161670.0    2017-01-31
4098029   93436  2017/02/28  0.000000  249.99001  161670.0    2017-02-28
4098030   93436  2017/03/31  0.000000  278.29999  164164.0    2017-03-31
4098031   93436  2017/04/28  0.000000  314.07001  164260.0    2017-04-28
4098032   93436  2017/05/31  0.000000  341.01001  164260.0    2017-05-31
4098033   93436  2017/06/30  0.000000  361.60999  166863.0    2017-06-30
4098034   93436  2017/07/31  0.000000  323.47000  166887.0    2017-07-31
4098035   93436  2017/08/31  0.000000  355.89999  166887.0    2017-08-31
4098036   93436  2017/09/29  0.000000  341.10001  168017.0    2017-09-29
4098037   93436  2017/10/31  0.000000  331.53000  168067.0    2017-10-31
4098038   93436  2017/11/30  0.000000  308.85001  168067.0    2017-11-30
4098039   93436  2017/12/29  0.000000  311.35001  168797.0    2017-12-29
4098040   93436  2018/01/31  0.000000  354.31000  168797.0    2018-01-31
4098041   93436  2018/02/28  0.000000  343.06000  168920.0    2018-02-28
4098042   93436  2018/03/29  0.000000  266.13000  169750.0    2018-03-29
4098043   93436  2018/04/30  0.000000  293.89999  169794.0    2018-04-30
4098044   93436  2018/05/31  0.000000  284.73001  169794.0    2018-05-31
4098045   93436  2018/06/29  0.000000  342.95001  170516.0    2018-06-29

[4098046 rows x 6 columns]

In [5]:
head, mid, tail = [], [], []

for i1 in range(1964, 2018):
    for i2 in range(2,13):
        mid.append(datetime.datetime(i1, i2, 1)-datetime.timedelta(days = 1))
    mid.append(datetime.datetime(i1+1, 1, 1)-datetime.timedelta(days = 1))

for i1 in range(8, 13):
    head.append(datetime.datetime(1963, i1, 1)-datetime.timedelta(days = 1))
head.append(datetime.datetime(1964, 1, 1)-datetime.timedelta(days = 1))
    
for i1 in range(2, 8):
    tail.append(datetime.datetime(2018,i1,1)-datetime.timedelta(days = 1))

dates_month = head+mid+tail # The index of the data file, in months

In [6]:
data

         PERMNO        date    DIVAMT        PRC    SHROUT datetime date
0         10000  1985/12/31  0.000000        NaN       NaN    1985-12-31
1         10000  1986/01/31  0.000000    4.37500    3680.0    1986-01-31
2         10000  1986/02/28  0.000000    3.25000    3680.0    1986-02-28
3         10000  1986/03/31  0.000000    4.43750    3680.0    1986-03-31
4         10000  1986/04/30  0.000000    4.00000    3793.0    1986-04-30
5         10000  1986/05/30  0.000000    3.10938    3793.0    1986-05-30
6         10000  1986/06/30  0.000000    3.09375    3793.0    1986-06-30
7         10000  1986/07/31  0.000000    2.84375    3793.0    1986-07-31
8         10000  1986/08/29  0.000000    1.09375    3793.0    1986-08-29
9         10000  1986/09/30  0.000000    1.03125    3793.0    1986-09-30
10        10000  1986/10/31  0.000000    0.78125    3843.0    1986-10-31
11        10000  1986/11/28  0.000000    0.82813    3843.0    1986-11-28
12        10000  1986/12/31  0.000000    0.51563    3843.0    1986-12-31
13        10000  1987/01/30  0.000000    0.40625    3893.0    1987-01-30
14        10000  1987/02/27  0.000000    0.40625    3893.0    1987-02-27
15        10000  1987/03/31  0.000000    0.25000    3893.0    1987-03-31
16        10000  1987/04/30  0.000000    0.23438    3893.0    1987-04-30
17        10000  1987/05/29  0.000000    0.21875    3893.0    1987-05-29
18        10000  1987/06/30  0.000000        NaN    3893.0    1987-06-30
19        10001  1985/12/31  0.000000        NaN       NaN    1985-12-31
20        10001  1986/01/31  0.000000    6.12500     985.0    1986-01-31
21        10001  1986/02/28  0.000000    6.25000     985.0    1986-02-28
22        10001  1986/03/31  0.031667    6.31250     985.0    1986-03-31
23        10001  1986/04/30  0.031667    6.37500     985.0    1986-04-30
24        10001  1986/05/30  0.031667    6.31250     985.0    1986-05-30
25        10001  1986/06/30  0.035000    6.12500     985.0    1986-06-30
26        10001  1986/07/31  0.035000    6.06250     985.0    1986-07-31
27        10001  1986/08/29  0.035000    6.50000     985.0    1986-08-29
28        10001  1986/09/30  0.035000    6.37500     991.0    1986-09-30
29        10001  1986/10/31  0.035000    6.62500     991.0    1986-10-31
...         ...         ...       ...        ...       ...           ...
4098016   93436  2016/01/29  0.000000  191.20000  132056.0    2016-01-29
4098017   93436  2016/02/29  0.000000  191.92999  132056.0    2016-02-29
4098018   93436  2016/03/31  0.000000  229.77000  133858.0    2016-03-31
4098019   93436  2016/04/29  0.000000  240.75999  133945.0    2016-04-29
4098020   93436  2016/05/31  0.000000  223.23000  147543.0    2016-05-31
4098021   93436  2016/06/30  0.000000  212.28000  148015.0    2016-06-30
4098022   93436  2016/07/29  0.000000  234.78999  148693.0    2016-07-29
4098023   93436  2016/08/31  0.000000  212.00999  149239.0    2016-08-31
4098024   93436  2016/09/30  0.000000  204.03000  149825.0    2016-09-30
4098025   93436  2016/10/31  0.000000  197.73000  149891.0    2016-10-31
4098026   93436  2016/11/30  0.000000  189.39999  149964.0    2016-11-30
4098027   93436  2016/12/30  0.000000  213.69000  161561.0    2016-12-30
4098028   93436  2017/01/31  0.000000  251.92999  161670.0    2017-01-31
4098029   93436  2017/02/28  0.000000  249.99001  161670.0    2017-02-28
4098030   93436  2017/03/31  0.000000  278.29999  164164.0    2017-03-31
4098031   93436  2017/04/28  0.000000  314.07001  164260.0    2017-04-28
4098032   93436  2017/05/31  0.000000  341.01001  164260.0    2017-05-31
4098033   93436  2017/06/30  0.000000  361.60999  166863.0    2017-06-30
4098034   93436  2017/07/31  0.000000  323.47000  166887.0    2017-07-31
4098035   93436  2017/08/31  0.000000  355.89999  166887.0    2017-08-31
4098036   93436  2017/09/29  0.000000  341.10001  168017.0    2017-09-29
4098037   93436  2017/10/31  0.000000  331.53000  168067.0    2017-10-31
4098038   93436  2017/11/30  0.000000  308.85001  168067.0    2017-11-30
4098039   93436  2017/12/29  0.000000  311.35001  168797.0    2017-12-29
4098040   93436  2018/01/31  0.000000  354.31000  168797.0    2018-01-31
4098041   93436  2018/02/28  0.000000  343.06000  168920.0    2018-02-28
4098042   93436  2018/03/29  0.000000  266.13000  169750.0    2018-03-29
4098043   93436  2018/04/30  0.000000  293.89999  169794.0    2018-04-30
4098044   93436  2018/05/31  0.000000  284.73001  169794.0    2018-05-31
4098045   93436  2018/06/29  0.000000  342.95001  170516.0    2018-06-29

[4098046 rows x 6 columns]

In [7]:
data['PRC'] = data['PRC'].fillna(-1)
data['SHROUT'] = data['SHROUT'].fillna(-1)
data = data.drop(columns=['datetime date'])

In [8]:
# make sure the dates are aligned to the last day of the month
def find_match_date(date):
    date = datetime.datetime.strptime(date,'%Y/%m/%d')
    if date not in dates_month:
        if date.month<=11:
            return datetime.datetime(date.year, date.month+1, 1) - datetime.timedelta(days=1)
        else:
            return datetime.datetime(date.year+1, 1, 1) - datetime.timedelta(days=1)
    else:
        return date

data['date'] = data['date'].apply(find_match_date)
data

         PERMNO       date    DIVAMT        PRC    SHROUT
0         10000 1985-12-31  0.000000   -1.00000      -1.0
1         10000 1986-01-31  0.000000    4.37500    3680.0
2         10000 1986-02-28  0.000000    3.25000    3680.0
3         10000 1986-03-31  0.000000    4.43750    3680.0
4         10000 1986-04-30  0.000000    4.00000    3793.0
5         10000 1986-05-31  0.000000    3.10938    3793.0
6         10000 1986-06-30  0.000000    3.09375    3793.0
7         10000 1986-07-31  0.000000    2.84375    3793.0
8         10000 1986-08-31  0.000000    1.09375    3793.0
9         10000 1986-09-30  0.000000    1.03125    3793.0
10        10000 1986-10-31  0.000000    0.78125    3843.0
11        10000 1986-11-30  0.000000    0.82813    3843.0
12        10000 1986-12-31  0.000000    0.51563    3843.0
13        10000 1987-01-31  0.000000    0.40625    3893.0
14        10000 1987-02-28  0.000000    0.40625    3893.0
15        10000 1987-03-31  0.000000    0.25000    3893.0
16        10000 1987-04-30  0.000000    0.23438    3893.0
17        10000 1987-05-31  0.000000    0.21875    3893.0
18        10000 1987-06-30  0.000000   -1.00000    3893.0
19        10001 1985-12-31  0.000000   -1.00000      -1.0
20        10001 1986-01-31  0.000000    6.12500     985.0
21        10001 1986-02-28  0.000000    6.25000     985.0
22        10001 1986-03-31  0.031667    6.31250     985.0
23        10001 1986-04-30  0.031667    6.37500     985.0
24        10001 1986-05-31  0.031667    6.31250     985.0
25        10001 1986-06-30  0.035000    6.12500     985.0
26        10001 1986-07-31  0.035000    6.06250     985.0
27        10001 1986-08-31  0.035000    6.50000     985.0
28        10001 1986-09-30  0.035000    6.37500     991.0
29        10001 1986-10-31  0.035000    6.62500     991.0
...         ...        ...       ...        ...       ...
4098016   93436 2016-01-31  0.000000  191.20000  132056.0
4098017   93436 2016-02-29  0.000000  191.92999  132056.0
4098018   93436 2016-03-31  0.000000  229.77000  133858.0
4098019   93436 2016-04-30  0.000000  240.75999  133945.0
4098020   93436 2016-05-31  0.000000  223.23000  147543.0
4098021   93436 2016-06-30  0.000000  212.28000  148015.0
4098022   93436 2016-07-31  0.000000  234.78999  148693.0
4098023   93436 2016-08-31  0.000000  212.00999  149239.0
4098024   93436 2016-09-30  0.000000  204.03000  149825.0
4098025   93436 2016-10-31  0.000000  197.73000  149891.0
4098026   93436 2016-11-30  0.000000  189.39999  149964.0
4098027   93436 2016-12-31  0.000000  213.69000  161561.0
4098028   93436 2017-01-31  0.000000  251.92999  161670.0
4098029   93436 2017-02-28  0.000000  249.99001  161670.0
4098030   93436 2017-03-31  0.000000  278.29999  164164.0
4098031   93436 2017-04-30  0.000000  314.07001  164260.0
4098032   93436 2017-05-31  0.000000  341.01001  164260.0
4098033   93436 2017-06-30  0.000000  361.60999  166863.0
4098034   93436 2017-07-31  0.000000  323.47000  166887.0
4098035   93436 2017-08-31  0.000000  355.89999  166887.0
4098036   93436 2017-09-30  0.000000  341.10001  168017.0
4098037   93436 2017-10-31  0.000000  331.53000  168067.0
4098038   93436 2017-11-30  0.000000  308.85001  168067.0
4098039   93436 2017-12-31  0.000000  311.35001  168797.0
4098040   93436 2018-01-31  0.000000  354.31000  168797.0
4098041   93436 2018-02-28  0.000000  343.06000  168920.0
4098042   93436 2018-03-31  0.000000  266.13000  169750.0
4098043   93436 2018-04-30  0.000000  293.89999  169794.0
4098044   93436 2018-05-31  0.000000  284.73001  169794.0
4098045   93436 2018-06-30  0.000000  342.95001  170516.0

[4098046 rows x 5 columns]

In [9]:
# Record dates
cur_tic = data['PERMNO'][0]
start_ind = 0
dates_ind = {}
dates = {}

for i in range(len(data)):
    if data['PERMNO'][i]==cur_tic:
        pass
    else:
        dates_ind.update({cur_tic:[start_ind, i-1]})
        dates.update({cur_tic:[data['date'][start_ind],data['date'][i-1]]})
        start_ind=i
        cur_tic = data['PERMNO'][i]
        
dates_ind.update({cur_tic:[start_ind, i-1]})
dates.update({cur_tic:[data['date'][start_ind],data['date'][i-1]]})

In [10]:
dates

{10000: [Timestamp('1985-12-31 00:00:00'), Timestamp('1987-06-30 00:00:00')],
 10001: [Timestamp('1985-12-31 00:00:00'), Timestamp('2017-08-31 00:00:00')],
 10002: [Timestamp('1985-12-31 00:00:00'), Timestamp('2013-02-28 00:00:00')],
 10003: [Timestamp('1985-12-31 00:00:00'), Timestamp('1995-12-31 00:00:00')],
 10005: [Timestamp('1985-12-31 00:00:00'), Timestamp('1991-07-31 00:00:00')],
 10006: [Timestamp('1963-07-31 00:00:00'), Timestamp('1984-06-30 00:00:00')],
 10007: [Timestamp('1985-12-31 00:00:00'), Timestamp('1990-10-31 00:00:00')],
 10008: [Timestamp('1985-12-31 00:00:00'), Timestamp('1988-11-30 00:00:00')],
 10009: [Timestamp('1985-12-31 00:00:00'), Timestamp('2000-11-30 00:00:00')],
 10010: [Timestamp('1985-12-31 00:00:00'), Timestamp('1995-08-31 00:00:00')],
 10011: [Timestamp('1988-05-31 00:00:00'), Timestamp('1998-02-28 00:00:00')],
 10012: [Timestamp('1985-12-31 00:00:00'), Timestamp('2005-08-31 00:00:00')],
 10013: [Timestamp('1985-12-31 00:00:00'), Timestamp('1987-06-30 00:00:00')],
 10014: [Timestamp('1963-07-31 00:00:00'), Timestamp('1977-04-30 00:00:00')],
 10015: [Timestamp('1983-08-31 00:00:00'), Timestamp('1986-07-31 00:00:00')],
 10016: [Timestamp('1985-12-31 00:00:00'), Timestamp('2001-05-31 00:00:00')],
 10017: [Timestamp('1985-12-31 00:00:00'), Timestamp('1988-09-30 00:00:00')],
 10018: [Timestamp('1985-12-31 00:00:00'), Timestamp('1995-11-30 00:00:00')],
 10019: [Timestamp('1985-12-31 00:00:00'), Timestamp('2002-06-30 00:00:00')],
 10020: [Timestamp('1985-12-31 00:00:00'), Timestamp('1993-05-31 00:00:00')],
 10021: [Timestamp('1985-12-31 00:00:00'), Timestamp('1996-01-31 00:00:00')],
 10023: [Timestamp('1972-11-30 00:00:00'), Timestamp('1973-06-30 00:00:00')],
 10024: [Timestamp('1985-12-31 00:00:00'), Timestamp('1992-05-31 00:00:00')],
 10025: [Timestamp('1985-12-31 00:00:00'), Timestamp('2017-01-31 00:00:00')],
 10026: [Timestamp('1986-01-31 00:00:00'), Timestamp('2018-06-30 00:00:00')],
 10027: [Timestamp('1986-01-31 00:00:00'), Timestamp('1990-03-31 00:00:00')],
 10028: [Timestamp('1986-01-31 00:00:00'), Timestamp('2018-06-30 00:00:00')],
 10029: [Timestamp('1986-01-31 00:00:00'), Timestamp('1990-08-31 00:00:00')],
 10030: [Timestamp('1963-07-31 00:00:00'), Timestamp('1968-12-31 00:00:00')],
 10031: [Timestamp('1983-11-30 00:00:00'), Timestamp('1989-08-31 00:00:00')],
 10032: [Timestamp('1986-01-31 00:00:00'), Timestamp('2018-06-30 00:00:00')],
 10033: [Timestamp('1986-01-31 00:00:00'), Timestamp('1986-12-31 00:00:00')],
 10034: [Timestamp('1986-01-31 00:00:00'), Timestamp('1991-09-30 00:00:00')],
 10035: [Timestamp('1986-01-31 00:00:00'), Timestamp('2003-12-31 00:00:00')],
 10036: [Timestamp('1986-01-31 00:00:00'), Timestamp('1991-03-31 00:00:00')],
 10037: [Timestamp('1986-01-31 00:00:00'), Timestamp('2004-06-30 00:00:00')],
 10038: [Timestamp('1986-01-31 00:00:00'), Timestamp('1991-01-31 00:00:00')],
 10039: [Timestamp('1986-01-31 00:00:00'), Timestamp('2001-06-30 00:00:00')],
 10040: [Timestamp('1986-01-31 00:00:00'), Timestamp('1989-06-30 00:00:00')],
 10041: [Timestamp('1986-01-31 00:00:00'), Timestamp('1990-05-31 00:00:00')],
 10042: [Timestamp('1986-01-31 00:00:00'), Timestamp('2008-03-31 00:00:00')],
 10043: [Timestamp('1986-01-31 00:00:00'), Timestamp('1999-06-30 00:00:00')],
 10044: [Timestamp('1986-01-31 00:00:00'), Timestamp('2018-06-30 00:00:00')],
 10045: [Timestamp('1986-01-31 00:00:00'), Timestamp('1987-04-30 00:00:00')],
 10046: [Timestamp('1986-01-31 00:00:00'), Timestamp('1995-03-31 00:00:00')],
 10047: [Timestamp('1986-01-31 00:00:00'), Timestamp('1995-01-31 00:00:00')],
 10048: [Timestamp('1986-01-31 00:00:00'), Timestamp('1999-10-31 00:00:00')],
 10050: [Timestamp('1972-12-31 00:00:00'), Timestamp('1979-06-30 00:00:00')],
 10051: [Timestamp('1986-01-31 00:00:00'), Timestamp('2018-06-30 00:00:00')],
 10052: [Timestamp('1986-01-31 00:00:00'), Timestamp('1988-03-31 00:00:00')],
 10053: [Timestamp('1986-01-31 00:00:00'), Timestamp('1990-01-31 00:00:00')],
 10054: [Timestamp('1986-01-31 00:00:00'), Timestamp('1987-01-31 00:00:00')],
 10055: [Timestamp('1986-01-31 00:00:00'), Timestamp('1995-08-31 00:00:00')],
 10056: [Timestamp('1986-01-31 00:00:00'), Timestamp('2006-10-31 00:00:00')],
 10057: [Timestamp('1963-07-31 00:00:00'), Timestamp('1996-07-31 00:00:00')],
 10058: [Timestamp('1972-11-30 00:00:00'), Timestamp('1984-09-30 00:00:00')],
 10059: [Timestamp('1986-01-31 00:00:00'), Timestamp('1994-04-30 00:00:00')],
 10060: [Timestamp('1986-01-31 00:00:00'), Timestamp('1998-06-30 00:00:00')],
 10061: [Timestamp('1986-01-31 00:00:00'), Timestamp('1990-08-31 00:00:00')],
 10062: [Timestamp('1986-01-31 00:00:00'), Timestamp('1999-09-30 00:00:00')],
 10063: [Timestamp('1986-01-31 00:00:00'), Timestamp('1993-07-31 00:00:00')],
 10064: [Timestamp('1986-01-31 00:00:00'), Timestamp('1997-03-31 00:00:00')],
 10065: [Timestamp('1963-07-31 00:00:00'), Timestamp('2018-06-30 00:00:00')],
 10066: [Timestamp('1983-07-31 00:00:00'), Timestamp('2008-01-31 00:00:00')],
 10067: [Timestamp('1986-01-31 00:00:00'), Timestamp('1987-03-31 00:00:00')],
 10068: [Timestamp('1986-01-31 00:00:00'), Timestamp('1988-03-31 00:00:00')],
 10069: [Timestamp('1986-01-31 00:00:00'), Timestamp('1987-01-31 00:00:00')],
 10070: [Timestamp('1986-01-31 00:00:00'), Timestamp('1990-11-30 00:00:00')],
 10071: [Timestamp('1986-02-28 00:00:00'), Timestamp('1997-09-30 00:00:00')],
 10072: [Timestamp('1986-02-28 00:00:00'), Timestamp('1992-10-31 00:00:00')],
 10074: [Timestamp('1981-12-31 00:00:00'), Timestamp('1996-03-31 00:00:00')],
 10075: [Timestamp('1986-02-28 00:00:00'), Timestamp('1999-07-31 00:00:00')],
 10076: [Timestamp('1986-02-28 00:00:00'), Timestamp('1990-06-30 00:00:00')],
 10077: [Timestamp('1986-03-31 00:00:00'), Timestamp('1994-01-31 00:00:00')],
 10078: [Timestamp('1986-02-28 00:00:00'), Timestamp('2010-01-31 00:00:00')],
 10079: [Timestamp('1986-02-28 00:00:00'), Timestamp('1995-03-31 00:00:00')],
 10080: [Timestamp('1986-02-28 00:00:00'), Timestamp('2003-11-30 00:00:00')],
 10082: [Timestamp('1983-02-28 00:00:00'), Timestamp('1995-09-30 00:00:00')],
 10083: [Timestamp('1986-02-28 00:00:00'), Timestamp('1993-09-30 00:00:00')],
 10084: [Timestamp('1986-02-28 00:00:00'), Timestamp('1994-03-31 00:00:00')],
 10085: [Timestamp('1986-02-28 00:00:00'), Timestamp('2006-04-30 00:00:00')],
 10086: [Timestamp('1986-02-28 00:00:00'), Timestamp('1994-07-31 00:00:00')],
 10087: [Timestamp('1986-02-28 00:00:00'), Timestamp('2000-10-31 00:00:00')],
 10088: [Timestamp('1986-02-28 00:00:00'), Timestamp('1988-05-31 00:00:00')],
 10089: [Timestamp('1986-02-28 00:00:00'), Timestamp('2005-03-31 00:00:00')],
 10090: [Timestamp('1986-02-28 00:00:00'), Timestamp('1995-08-31 00:00:00')],
 10091: [Timestamp('1986-02-28 00:00:00'), Timestamp('1989-02-28 00:00:00')],
 10092: [Timestamp('1986-02-28 00:00:00'), Timestamp('2010-05-31 00:00:00')],
 10093: [Timestamp('1986-02-28 00:00:00'), Timestamp('1990-05-31 00:00:00')],
 10094: [Timestamp('1986-02-28 00:00:00'), Timestamp('1997-12-31 00:00:00')],
 10095: [Timestamp('1986-02-28 00:00:00'), Timestamp('1994-12-31 00:00:00')],
 10096: [Timestamp('1986-02-28 00:00:00'), Timestamp('1990-03-31 00:00:00')],
 10097: [Timestamp('1986-02-28 00:00:00'), Timestamp('1996-04-30 00:00:00')],
 10098: [Timestamp('1986-02-28 00:00:00'), Timestamp('1989-04-30 00:00:00')],
 10099: [Timestamp('1986-02-28 00:00:00'), Timestamp('1987-09-30 00:00:00')],
 10100: [Timestamp('1986-02-28 00:00:00'), Timestamp('2013-03-31 00:00:00')],
 10101: [Timestamp('1986-02-28 00:00:00'), Timestamp('1988-07-31 00:00:00')],
 10102: [Timestamp('1963-07-31 00:00:00'), Timestamp('1978-05-31 00:00:00')],
 10103: [Timestamp('1977-02-28 00:00:00'), Timestamp('1989-12-31 00:00:00')],
 10104: [Timestamp('1986-02-28 00:00:00'), Timestamp('2018-06-30 00:00:00')],
 10105: [Timestamp('1986-02-28 00:00:00'), Timestamp('1987-08-31 00:00:00')],
 10106: [Timestamp('1986-02-28 00:00:00'), Timestamp('1995-01-31 00:00:00')],
 10107: [Timestamp('1986-02-28 00:00:00'), Timestamp('2018-06-30 00:00:00')],
 10108: [Timestamp('1986-02-28 00:00:00'), Timestamp('2005-08-31 00:00:00')],
 10109: [Timestamp('1986-02-28 00:00:00'), Timestamp('1990-08-31 00:00:00')],
 10111: [Timestamp('1972-11-30 00:00:00'), Timestamp('1973-03-31 00:00:00')],
 10112: [Timestamp('1986-02-28 00:00:00'), Timestamp('1988-06-30 00:00:00')],
 10113: [Timestamp('2010-06-30 00:00:00'), Timestamp('2018-06-30 00:00:00')],
 10114: [Timestamp('1988-05-31 00:00:00'), Timestamp('2004-08-31 00:00:00')],
 10115: [Timestamp('1986-02-28 00:00:00'), Timestamp('1988-06-30 00:00:00')],
 10116: [Timestamp('1986-02-28 00:00:00'), Timestamp('2017-02-28 00:00:00')],
 10117: [Timestamp('1986-02-28 00:00:00'), Timestamp('1987-10-31 00:00:00')],
 10118: [Timestamp('1986-02-28 00:00:00'), Timestamp('1988-11-30 00:00:00')],
 10119: [Timestamp('1986-02-28 00:00:00'), Timestamp('2007-09-30 00:00:00')],
 10120: [Timestamp('1986-02-28 00:00:00'), Timestamp('1998-05-31 00:00:00')],
 10121: [Timestamp('1986-02-28 00:00:00'), Timestamp('1992-01-31 00:00:00')],
 10122: [Timestamp('1986-02-28 00:00:00'), Timestamp('2002-10-31 00:00:00')],
 10123: [Timestamp('1988-03-31 00:00:00'), Timestamp('2002-06-30 00:00:00')],
 10124: [Timestamp('1986-02-28 00:00:00'), Timestamp('1987-12-31 00:00:00')],
 10125: [Timestamp('1986-02-28 00:00:00'), Timestamp('1991-08-31 00:00:00')],
 10126: [Timestamp('1986-02-28 00:00:00'), Timestamp('2000-07-31 00:00:00')],
 10127: [Timestamp('1986-02-28 00:00:00'), Timestamp('2002-04-30 00:00:00')],
 10128: [Timestamp('1986-02-28 00:00:00'), Timestamp('2001-02-28 00:00:00')],
 10130: [Timestamp('1986-02-28 00:00:00'), Timestamp('1999-07-31 00:00:00')],
 10131: [Timestamp('1986-02-28 00:00:00'), Timestamp('1991-09-30 00:00:00')],
 10132: [Timestamp('1986-02-28 00:00:00'), Timestamp('1989-11-30 00:00:00')],
 10133: [Timestamp('1986-02-28 00:00:00'), Timestamp('1990-10-31 00:00:00')],
 10134: [Timestamp('1986-03-31 00:00:00'), Timestamp('1988-11-30 00:00:00')],
 10135: [Timestamp('1986-03-31 00:00:00'), Timestamp('1989-02-28 00:00:00')],
 10136: [Timestamp('1986-03-31 00:00:00'), Timestamp('1996-03-31 00:00:00')],
 10137: [Timestamp('1963-07-31 00:00:00'), Timestamp('2011-02-28 00:00:00')],
 10138: [Timestamp('1986-03-31 00:00:00'), Timestamp('2018-06-30 00:00:00')],
 10139: [Timestamp('1988-05-31 00:00:00'), Timestamp('1989-10-31 00:00:00')],
 10140: [Timestamp('1986-03-31 00:00:00'), Timestamp('1998-07-31 00:00:00')],
 10141: [Timestamp('1986-03-31 00:00:00'), Timestamp('1996-07-31 00:00:00')],
 10142: [Timestamp('1986-03-31 00:00:00'), Timestamp('2000-04-30 00:00:00')],
 10143: [Timestamp('1986-03-31 00:00:00'), Timestamp('2010-06-30 00:00:00')],
 10144: [Timestamp('1986-03-31 00:00:00'), Timestamp('1988-09-30 00:00:00')],
 10145: [Timestamp('1963-07-31 00:00:00'), Timestamp('2018-06-30 00:00:00')],
 10146: [Timestamp('1972-11-30 00:00:00'), Timestamp('1988-04-30 00:00:00')],
 10147: [Timestamp('1986-03-31 00:00:00'), Timestamp('2016-09-30 00:00:00')],
 10148: [Timestamp('1986-03-31 00:00:00'), Timestamp('1991-04-30 00:00:00')],
 10149: [Timestamp('1986-03-31 00:00:00'), Timestamp('2002-07-31 00:00:00')],
 10150: [Timestamp('1986-03-31 00:00:00'), Timestamp('1998-02-28 00:00:00')],
 10151: [Timestamp('2010-06-30 00:00:00'), Timestamp('2015-08-31 00:00:00')],
 10152: [Timestamp('1986-03-31 00:00:00'), Timestamp('1990-05-31 00:00:00')],
 10153: [Timestamp('1963-07-31 00:00:00'), Timestamp('1988-12-31 00:00:00')],
 10154: [Timestamp('1972-11-30 00:00:00'), Timestamp('1996-02-29 00:00:00')],
 10155: [Timestamp('1986-03-31 00:00:00'), Timestamp('2001-06-30 00:00:00')],
 10156: [Timestamp('1986-03-31 00:00:00'), Timestamp('1991-05-31 00:00:00')],
 10157: [Timestamp('1986-03-31 00:00:00'), Timestamp('1997-01-31 00:00:00')],
 10158: [Timestamp('2010-06-30 00:00:00'), Timestamp('2018-06-30 00:00:00')],
 10159: [Timestamp('1986-03-31 00:00:00'), Timestamp('1990-06-30 00:00:00')],
 10160: [Timestamp('1986-03-31 00:00:00'), Timestamp('2003-06-30 00:00:00')],
 10161: [Timestamp('1963-07-31 00:00:00'), Timestamp('1993-11-30 00:00:00')],
 10162: [Timestamp('1972-12-31 00:00:00'), Timestamp('1981-03-31 00:00:00')],
 10163: [Timestamp('1986-03-31 00:00:00'), Timestamp('2012-05-31 00:00:00')],
 10164: [Timestamp('1986-03-31 00:00:00'), Timestamp('1989-09-30 00:00:00')],
 10165: [Timestamp('1986-03-31 00:00:00'), Timestamp('1988-02-29 00:00:00')],
 10166: [Timestamp('1986-03-31 00:00:00'), Timestamp('1992-10-31 00:00:00')],
 10167: [Timestamp('1986-03-31 00:00:00'), Timestamp('1987-06-30 00:00:00')],
 10168: [Timestamp('1986-03-31 00:00:00'), Timestamp('1989-04-30 00:00:00')],
 10169: [Timestamp('1986-03-31 00:00:00'), Timestamp('1987-09-30 00:00:00')],
 10170: [Timestamp('1986-03-31 00:00:00'), Timestamp('2003-05-31 00:00:00')],
 10171: [Timestamp('1986-03-31 00:00:00'), Timestamp('1990-05-31 00:00:00')],
 10172: [Timestamp('1986-03-31 00:00:00'), Timestamp('1991-12-31 00:00:00')],
 10173: [Timestamp('1986-03-31 00:00:00'), Timestamp('1996-02-29 00:00:00')],
 10174: [Timestamp('1986-03-31 00:00:00'), Timestamp('1993-03-31 00:00:00')],
 10175: [Timestamp('1986-03-31 00:00:00'), Timestamp('1997-07-31 00:00:00')],
 10176: [Timestamp('1986-03-31 00:00:00'), Timestamp('1992-06-30 00:00:00')],
 10177: [Timestamp('1986-03-31 00:00:00'), Timestamp('2003-07-31 00:00:00')],
 10178: [Timestamp('1986-03-31 00:00:00'), Timestamp('1999-02-28 00:00:00')],
 10179: [Timestamp('1986-03-31 00:00:00'), Timestamp('1997-10-31 00:00:00')],
 10180: [Timestamp('1988-03-31 00:00:00'), Timestamp('2018-06-30 00:00:00')],
 10181: [Timestamp('1986-03-31 00:00:00'), Timestamp('1990-03-31 00:00:00')],
 10182: [Timestamp('1986-03-31 00:00:00'), Timestamp('2018-06-30 00:00:00')],
 10183: [Timestamp('1986-03-31 00:00:00'), Timestamp('1986-10-31 00:00:00')],
 10184: [Timestamp('1988-02-29 00:00:00'), Timestamp('1992-04-30 00:00:00')],
 10185: [Timestamp('1986-03-31 00:00:00'), Timestamp('1999-11-30 00:00:00')],
 10186: [Timestamp('1986-03-31 00:00:00'), Timestamp('1990-04-30 00:00:00')],
 10187: [Timestamp('1986-03-31 00:00:00'), Timestamp('1998-03-31 00:00:00')],
 10188: [Timestamp('1963-07-31 00:00:00'), Timestamp('1978-08-31 00:00:00')],
 10189: [Timestamp('1972-11-30 00:00:00'), Timestamp('1988-02-29 00:00:00')],
 10190: [Timestamp('1986-03-31 00:00:00'), Timestamp('1992-01-31 00:00:00')],
 10191: [Timestamp('1986-03-31 00:00:00'), Timestamp('1990-03-31 00:00:00')],
 10192: [Timestamp('1986-03-31 00:00:00'), Timestamp('2001-07-31 00:00:00')],
 10193: [Timestamp('1986-03-31 00:00:00'), Timestamp('1994-08-31 00:00:00')],
 10194: [Timestamp('1986-03-31 00:00:00'), Timestamp('2000-10-31 00:00:00')],
 10195: [Timestamp('1986-03-31 00:00:00'), Timestamp('2003-09-30 00:00:00')],
 10196: [Timestamp('1963-07-31 00:00:00'), Timestamp('1968-01-31 00:00:00')],
 10197: [Timestamp('1972-11-30 00:00:00'), Timestamp('1973-02-28 00:00:00')],
 10198: [Timestamp('1986-03-31 00:00:00'), Timestamp('1991-10-31 00:00:00')],
 10199: [Timestamp('1986-03-31 00:00:00'), Timestamp('1998-04-30 00:00:00')],
 10200: [Timestamp('1986-03-31 00:00:00'), Timestamp('2018-06-30 00:00:00')],
 10201: [Timestamp('2010-06-30 00:00:00'), Timestamp('2018-06-30 00:00:00')],
 10202: [Timestamp('1986-03-31 00:00:00'), Timestamp('1988-08-31 00:00:00')],
 10203: [Timestamp('1986-04-30 00:00:00'), Timestamp('1993-09-30 00:00:00')],
 10204: [Timestamp('1986-04-30 00:00:00'), Timestamp('1987-05-31 00:00:00')],
 10205: [Timestamp('1986-04-30 00:00:00'), Timestamp('2010-12-31 00:00:00')],
 10206: [Timestamp('1986-04-30 00:00:00'), Timestamp('1990-05-31 00:00:00')],
 10207: [Timestamp('1988-05-31 00:00:00'), Timestamp('2018-06-30 00:00:00')],
 10208: [Timestamp('1986-04-30 00:00:00'), Timestamp('1992-05-31 00:00:00')],
 10209: [Timestamp('1963-07-31 00:00:00'), Timestamp('1963-10-31 00:00:00')],
 10210: [Timestamp('1986-04-30 00:00:00'), Timestamp('1991-11-30 00:00:00')],
 10211: [Timestamp('1986-04-30 00:00:00'), Timestamp('2006-03-31 00:00:00')],
 10212: [Timestamp('1986-04-30 00:00:00'), Timestamp('1996-06-30 00:00:00')],
 10213: [Timestamp('1986-04-30 00:00:00'), Timestamp('1996-12-31 00:00:00')],
 10214: [Timestamp('1986-04-30 00:00:00'), Timestamp('1998-01-31 00:00:00')],
 10215: [Timestamp('1986-04-30 00:00:00'), Timestamp('1987-08-31 00:00:00')],
 10216: [Timestamp('1986-04-30 00:00:00'), Timestamp('2001-05-31 00:00:00')],
 10217: [Timestamp('1963-07-31 00:00:00'), Timestamp('1970-01-31 00:00:00')],
 10218: [Timestamp('1980-09-30 00:00:00'), Timestamp('1999-03-31 00:00:00')],
 10219: [Timestamp('1986-04-30 00:00:00'), Timestamp('1987-05-31 00:00:00')],
 10220: [Timestamp('2010-07-31 00:00:00'), Timestamp('2018-06-30 00:00:00')],
 10221: [Timestamp('1986-04-30 00:00:00'), Timestamp('1988-06-30 00:00:00')],
 10222: [Timestamp('1986-04-30 00:00:00'), Timestamp('1996-02-29 00:00:00')],
 10223: [Timestamp('2010-06-30 00:00:00'), Timestamp('2014-03-31 00:00:00')],
 10224: [Timestamp('1986-04-30 00:00:00'), Timestamp('1993-05-31 00:00:00')],
 10225: [Timestamp('1963-07-31 00:00:00'), Timestamp('2014-05-31 00:00:00')],
 10226: [Timestamp('1972-11-30 00:00:00'), Timestamp('1973-10-31 00:00:00')],
 10227: [Timestamp('1986-04-30 00:00:00'), Timestamp('1988-11-30 00:00:00')],
 10228: [Timestamp('1986-04-30 00:00:00'), Timestamp('1990-06-30 00:00:00')],
 10229: [Timestamp('1986-04-30 00:00:00'), Timestamp('1988-03-31 00:00:00')],
 10230: [Timestamp('1986-04-30 00:00:00'), Timestamp('2001-11-30 00:00:00')],
 10231: [Timestamp('1986-04-30 00:00:00'), Timestamp('1997-09-30 00:00:00')],
 10232: [Timestamp('1986-04-30 00:00:00'), Timestamp('2018-06-30 00:00:00')],
 10233: [Timestamp('1963-07-31 00:00:00'), Timestamp('1986-01-31 00:00:00')],
 10234: [Timestamp('1972-11-30 00:00:00'), Timestamp('1983-07-31 00:00:00')],
 10235: [Timestamp('1986-04-30 00:00:00'), Timestamp('2001-08-31 00:00:00')],
 10236: [Timestamp('1986-04-30 00:00:00'), Timestamp('1990-10-31 00:00:00')],
 10237: [Timestamp('1986-04-30 00:00:00'), Timestamp('1988-09-30 00:00:00')],
 10238: [Timestamp('1986-04-30 00:00:00'), Timestamp('2008-02-29 00:00:00')],
 10239: [Timestamp('1986-04-30 00:00:00'), Timestamp('2018-06-30 00:00:00')],
 10240: [Timestamp('1986-04-30 00:00:00'), Timestamp('1988-05-31 00:00:00')],
 10241: [Timestamp('1963-07-31 00:00:00'), Timestamp('1988-12-31 00:00:00')],
 10242: [Timestamp('1986-04-30 00:00:00'), Timestamp('1998-08-31 00:00:00')],
 10243: [Timestamp('1986-04-30 00:00:00'), Timestamp('1995-04-30 00:00:00')],
 10244: [Timestamp('1986-04-30 00:00:00'), Timestamp('2002-06-30 00:00:00')],
 10245: [Timestamp('1986-04-30 00:00:00'), Timestamp('1992-11-30 00:00:00')],
 10246: [Timestamp('1986-04-30 00:00:00'), Timestamp('1996-03-31 00:00:00')],
 10247: [Timestamp('1986-04-30 00:00:00'), Timestamp('2000-03-31 00:00:00')],
 10248: [Timestamp('1986-04-30 00:00:00'), Timestamp('1996-02-29 00:00:00')],
 10249: [Timestamp('1986-04-30 00:00:00'), Timestamp('1988-10-31 00:00:00')],
 10250: [Timestamp('1986-04-30 00:00:00'), Timestamp('1997-12-31 00:00:00')],
 10251: [Timestamp('1986-04-30 00:00:00'), Timestamp('1992-11-30 00:00:00')],
 10252: [Timestamp('1986-04-30 00:00:00'), Timestamp('2018-06-30 00:00:00')],
 10253: [Timestamp('1986-04-30 00:00:00'), Timestamp('2018-06-30 00:00:00')],
 10254: [Timestamp('1986-04-30 00:00:00'), Timestamp('1987-08-31 00:00:00')],
 10255: [Timestamp('1986-04-30 00:00:00'), Timestamp('1988-09-30 00:00:00')],
 10256: [Timestamp('1986-04-30 00:00:00'), Timestamp('2001-07-31 00:00:00')],
 10257: [Timestamp('1986-04-30 00:00:00'), Timestamp('2018-06-30 00:00:00')],
 10258: [Timestamp('1986-04-30 00:00:00'), Timestamp('2018-06-30 00:00:00')],
 10259: [Timestamp('1986-04-30 00:00:00'), Timestamp('2018-06-30 00:00:00')],
 10260: [Timestamp('1986-04-30 00:00:00'), Timestamp('1990-08-31 00:00:00')],
 10261: [Timestamp('1986-04-30 00:00:00'), Timestamp('1994-01-31 00:00:00')],
 10262: [Timestamp('1986-04-30 00:00:00'), Timestamp('1990-12-31 00:00:00')],

In [11]:
start_time = time.time()
store = {}

def find_stocks(target_date):
    store = []
    for ticker in dates.keys():
        if dates[ticker][0] <= target_date and dates[ticker][1] >= target_date:
            store.append(ticker)
    return store

for i in dates_month:
    store.update({i:find_stocks(i)})
    
    
print(time.time()-start_time)

22.8979651927948

In [12]:
for date in store.keys():
    print(len(store[date]))

2092
2089
2091
2099
2102
2112
2113
2113
2128
2135
2142
2152
2153
2158
2161
2160
2164
2170
2172
2176
2182
2185
2194
2199
2205
2205
2212
2216
2216
2216
2215
2209
2206
2221
2227
2233
2238
2235
2232
2241
2240
2241
2235
2236
2240
2242
2250
2241
2247
2247
2258
2254
2251
2254
2255
2250
2256
2260
2263
2265
2259
2248
2257
2264
2267
2274
2284
2287
2301
2306
2319
2328
2345
2354
2359
2364
2376
2383
2396
2409
2420
2430
2437
2443
2442
2449
2460
2474
2481
2493
2493
2495
2510
2524
2531
2542
2549
2562
2572
2589
2610
2626
2638
2651
2666
2687
2691
2704
2722
2735
2737
2756
5751
5798
5843
5853
5844
5818
5794
5752
5731
5710
5691
5675
5661
5605
5556
5541
5534
5523
5508
5477
5451
5436
5411
5396
5377
5362
5348
5325
5329
5326
5331
5340
5330
5328
5321
5318
5321
5325
5314
5310
5315
5314
5315
5318
5323
5333
5336
5331
5333
5338
5317
5309
5311
5307
5314
5306
5301
5283
5272
5261
5254
5253
5236
5204
5204
5205
5202
5184
5170
5183
5172
5160
5155
5154
5144
5131
5119
5126
5117
5114
5098
5084
5074
5076
5092
5109
5110
5095
5096
5108
5121
5145
5167
5202
5223
5237
5277
5309
5318
5346
5394
5440
5491
5552
5566
5589
5617
5635
5654
5657
5654
5651
5648
5639
5627
5629
5619
5611
5608
5785
5810
5806
5809
5828
5861
5903
5975
6049
6120
6189
6252
6307
6414
6468
6503
6533
6545
6570
6604
6611
6614
6609
6620
6613
6606
6602
6587
6571
6580
6587
6607
6614
6614
6631
6645
6674
6690
6667
6653
6640
6671
6723
6797
6854
6893
6922
6970
7022
7082
7090
7073
7108
7163
7209
7299
7387
7442
7488
7506
7492
7468
7430
7413
7404
7384
7380
7382
7346
7341
7331
7326
7287
7286
7268
7211
7183
7166
7151
7156
7144
7105
7096
7068
7065
7075
7051
7027
7024
7039
7042
7040
7048
7026
6995
6962
6945
6919
6898
6880
6874
6875
6897
6894
6918
6950
6940
6970
7015
7036
7045
7049
7118
7141
7154
7171
7180
7163
7109
7121
7150
7182
7203
7241
7303
7351
7395
7478
7548
7608
7654
7728
7839
7965
8019
8069
8137
8174
8248
8300
8329
8358
8377
8410
8429
8446
8441
8428
8422
8442
8446
8479
8513
8540
8535
8582
8644
8702
8699
8726
8780
8827
8914
8978
9027
9077
9089
9166
9236
9268
9275
9290
9289
9288
9285
9318
9355
9339
9325
9350
9387
9383
9372
9337
9328
9331
9318
9330
9335
9277
9204
9139
9096
9041
8997
8924
8880
8864
8819
8802
8811
8793
8753
8754
8755
8735
8659
8649
8669
8666
8631
8657
8677
8673
8645
8643
8594
8521
8441
8366
8293
8239
8182
8117
8046
7980
7924
7847
7830
7802
7734
7679
7639
7605
7572
7518
7494
7456
7416
7382
7385
7340
7314
7264
7218
7179
7123
7097
7067
7044
7020
6993
6994
6997
6974
6984
6977
6971
6980
6974
6990
6978
6958
6972
6985
6996
6982
6982
6979
6975
6981
6995
6996
7014
6999
6992
6998
6998
6976
6968
6956
6951
6970
7012
7001
6994
7000
7040
7073
7083
7084
7124
7126
7143
7187
7196
7204
7185
7159
7180
7204
7210
7185
7169
7164
7142
7141
7132
7122
7103
7070
7040
7022
6988
6955
6911
6876
6840
6807
6790
6759
6728
6727
6730
6752
6754
6750
6736
6741
6763
6748
6768
6773
6764
6752
6756
6765
6779
6786
6768
6782
6812
6844
6849
6855
6837
6835
6845
6859
6852
6854
6881
6891
6898
6900
6895
6904
6897
6873
6863
6850
6805
6797
6772
6773
6781
6794
6804
6820
6830
6840
6890
6930
6919
6927
6952
6985
6997
7017
7060
7095
7118
7133
7176
7199
7196
7189
7187
7179
7190
7208
7256
7319
7342
7347
7352
7369
7356
7351
7327
7312
7323
7324
7316
7316
7307
7327
7308
7287
7288
7291
7271
7291
7304
7313
7334
7348
7343
7342
7381
7394
7388
7403
7408
7429
7499
7515
7484
7511

In [13]:
datetime.datetime(1963,7,31), datetime.datetime(2018, 6, 29, 0, 0)

(datetime.datetime(1963, 7, 31, 0, 0), datetime.datetime(2018, 6, 29, 0, 0))

In [14]:
# find the record of the company of a certain month
start_time = time.time()

def find_component(date,
                   start_time):
    date_df = []
    for stock in store[date]:
        data_slice = pd.DataFrame(data[dates_ind[stock][0]:dates_ind[stock][1]+1])
        n = np.where(data_slice['date']==date)
        date_df.append(data_slice.iloc[n])
    print(time.time()-start_time)
    return pd.concat(date_df)
frame = find_component(datetime.datetime(2018, 6, 30, 0, 0), start_time)

10.674474000930786

In [15]:
frame.sort_values(['DIVAMT'],ascending=False)

         PERMNO       date     DIVAMT        PRC     SHROUT
2491672   76477 2018-06-30  134.50000   -1.00000    57827.0
3626380   88668 2018-06-30  128.00000   -1.00000   441284.0
414055    14198 2018-06-30   84.00000   -1.00000    12502.0
3915086   91392 2018-06-30   61.40000   44.27000    99512.0
2611835   77418 2018-06-30   53.75000   -1.00000   782319.0
550107    16973 2018-06-30   52.95000   -1.00000    17443.0
560094    17256 2018-06-30   50.00000   -1.00000    30405.0
2611834   77418 2018-06-30   47.63655   -1.00000   782319.0
392551    13875 2018-06-30   45.25000   -1.00000    57117.0
294320    12438 2018-06-30   37.05000   -1.00000     4750.0
3055827   81565 2018-06-30   33.70000   -1.00000     1814.0
517089    16039 2018-06-30   33.59540   -1.00000      200.0
530552    16438 2018-06-30   32.46896   -1.00000      450.0
794351    24432 2018-06-30   32.45000   -1.00000   215796.0
495110    15557 2018-06-30   30.61000   -1.00000    13550.0
498621    15604 2018-06-30   30.28671   -1.00000       -1.0
3305803   84776 2018-06-30   30.00000   -1.00000    50730.0
3900037   91263 2018-06-30   28.82453   -1.00000       -1.0
499229    15620 2018-06-30   28.53000   -1.00000      350.0
499296    15622 2018-06-30   23.51000   -1.00000     1700.0
3456279   86486 2018-06-30   18.59000   -1.00000     8963.0
426831    14383 2018-06-30   17.77533   -1.00000       -1.0
2670769   77862 2018-06-30   15.53580   -1.00000    20068.0
3973101   91973 2018-06-30   14.97000   14.25000     1820.0
3695674   89359 2018-06-30   13.59168   -1.00000     2328.0
3663240   89052 2018-06-30   13.53000   -1.00000     7675.0
2648027   77669 2018-06-30   13.50000   -1.00000    40517.0
487353    15415 2018-06-30   12.48000   -1.00000    28093.0
1285045   40125 2018-06-30   12.27500   80.61000   284792.0
325370    12843 2018-06-30   12.12978   -1.00000       -1.0
...         ...        ...        ...        ...        ...
767802    23799 2018-06-30    0.00000    7.79000    49080.0
387513    13802 2018-06-30    0.00000   30.15000    53936.0
764702    23660 2018-06-30    0.00000  185.07001   106279.0
759924    23536 2018-06-30    0.00000   64.65000   315539.0
754815    23393 2018-06-30    0.00000   53.16000   244702.0
749467    23229 2018-06-30    0.00000   47.28000   282526.0
745507    23085 2018-06-30    0.00000   38.52000   142917.0
742084    23026 2018-06-30    0.00000   35.91000   476909.0
387148    13796 2018-06-30    0.00000    2.20000    21049.0
795609    24441 2018-06-30    0.00000    7.60000   186117.0
847200    25953 2018-06-30    0.00000   73.20000   154678.0
796273    24459 2018-06-30    0.00000    8.57000   187550.0
843211    25785 2018-06-30    0.00000   11.07000  3914102.0
842543    25778 2018-06-30    0.00000   35.65000   413233.0
385927    13777 2018-06-30    0.00000   14.57000    28964.0
836022    25582 2018-06-30    0.00000  144.53999   118729.0
833095    25487 2018-06-30    0.00000   32.50000    80000.0
830888    25419 2018-06-30    0.00000  146.23000    64525.0
828320    25320 2018-06-30    0.00000   40.54000   300646.0
826974    25304 2018-06-30    0.00000   22.10000    80575.0
824555    25232 2018-06-30    0.00000   69.83000   411076.0
386298    13783 2018-06-30    0.00000    2.42000    77947.0
386522    13788 2018-06-30    0.00000   85.19000   483865.0
386588    13789 2018-06-30    0.00000    8.75000    11937.0
813689    24969 2018-06-30    0.00000   52.66000    65669.0
812537    24942 2018-06-30    0.00000  193.17999   287250.0
387015    13794 2018-06-30    0.00000   32.35000    13708.0
803425    24643 2018-06-30    0.00000   17.01000   482832.0
797384    24476 2018-06-30    0.00000  156.42000    24299.0
4097922   93434 2018-06-30    0.00000    3.25000    25991.0

[7549 rows x 5 columns]