In [1]:
import pandas as pd
import numpy as np
import datetime
import time

In [2]:
data = pd.read_csv('with_36mvols.csv', low_memory=False, index_col=0)

D:\Anaconda3\lib\site-packages\numpy\lib\arraysetops.py:569: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)

In [3]:
data['Mkt Cap'] = data['PRC'] * data['SHROUT']
data

,PERMNO,date,DIVAMT,PRC,SHROUT,Rolling 36m Vol,Mkt Cap
0,10000,1985-12-31,0.000000,-1.00000,-1.0,NaN,1.000000e+00
1,10000,1986-01-31,0.000000,4.37500,3680.0,NaN,1.610000e+04
2,10000,1986-02-28,0.000000,3.25000,3680.0,NaN,1.196000e+04
3,10000,1986-03-31,0.000000,4.43750,3680.0,NaN,1.633000e+04
4,10000,1986-04-30,0.000000,4.00000,3793.0,NaN,1.517200e+04
5,10000,1986-05-31,0.000000,3.10938,3793.0,NaN,1.179388e+04
6,10000,1986-06-30,0.000000,3.09375,3793.0,NaN,1.173459e+04
7,10000,1986-07-31,0.000000,2.84375,3793.0,NaN,1.078634e+04
8,10000,1986-08-31,0.000000,1.09375,3793.0,NaN,4.148594e+03
9,10000,1986-09-30,0.000000,1.03125,3793.0,NaN,3.911531e+03
10,10000,1986-10-31,0.000000,0.78125,3843.0,NaN,3.002344e+03
11,10000,1986-11-30,0.000000,0.82813,3843.0,NaN,3.182504e+03
12,10000,1986-12-31,0.000000,0.51563,3843.0,NaN,1.981566e+03
13,10000,1987-01-31,0.000000,0.40625,3893.0,NaN,1.581531e+03
14,10000,1987-02-28,0.000000,0.40625,3893.0,NaN,1.581531e+03
15,10000,1987-03-31,0.000000,0.25000,3893.0,NaN,9.732500e+02
16,10000,1987-04-30,0.000000,0.23438,3893.0,NaN,9.124413e+02
17,10000,1987-05-31,0.000000,0.21875,3893.0,NaN,8.515938e+02
18,10000,1987-06-30,0.000000,-1.00000,3893.0,NaN,-3.893000e+03
19,10001,1985-12-31,0.000000,-1.00000,-1.0,NaN,1.000000e+00
20,10001,1986-01-31,0.000000,6.12500,985.0,NaN,6.033125e+03
21,10001,1986-02-28,0.000000,6.25000,985.0,NaN,6.156250e+03
22,10001,1986-03-31,0.031667,6.31250,985.0,NaN,6.217812e+03
23,10001,1986-04-30,0.031667,6.37500,985.0,NaN,6.279375e+03
24,10001,1986-05-31,0.031667,6.31250,985.0,NaN,6.217812e+03
25,10001,1986-06-30,0.035000,6.12500,985.0,NaN,6.033125e+03
26,10001,1986-07-31,0.035000,6.06250,985.0,NaN,5.971562e+03
27,10001,1986-08-31,0.035000,6.50000,985.0,NaN,6.402500e+03
28,10001,1986-09-30,0.035000,6.37500,991.0,NaN,6.317625e+03
29,10001,1986-10-31,0.035000,6.62500,991.0,NaN,6.565375e+03
...,...,...,...,...,...,...,...
4098016,93436,2016-01-31,0.000000,191.20000,132056.0,67.974093,2.524911e+07
4098017,93436,2016-02-29,0.000000,191.92999,132056.0,62.937431,2.534551e+07
4098018,93436,2016-03-31,0.000000,229.77000,133858.0,56.929345,3.075655e+07
4098019,93436,2016-04-30,0.000000,240.75999,133945.0,50.275961,3.224860e+07
4098020,93436,2016-05-31,0.000000,223.23000,147543.0,43.810568,3.293602e+07
4098021,93436,2016-06-30,0.000000,212.28000,148015.0,39.647662,3.142062e+07
4098022,93436,2016-07-31,0.000000,234.78999,148693.0,35.479931,3.491163e+07
4098023,93436,2016-08-31,0.000000,212.00999,149239.0,32.877783,3.164016e+07
4098024,93436,2016-09-30,0.000000,204.03000,149825.0,31.848610,3.056879e+07
4098025,93436,2016-10-31,0.000000,197.73000,149891.0,31.658101,2.963795e+07
4098026,93436,2016-11-30,0.000000,189.39999,149964.0,30.269247,2.840318e+07
4098027,93436,2016-12-31,0.000000,213.69000,161561.0,26.444773,3.452397e+07
4098028,93436,2017-01-31,0.000000,251.92999,161670.0,23.572926,4.072952e+07
4098029,93436,2017-02-28,0.000000,249.99001,161670.0,22.888288,4.041588e+07
4098030,93436,2017-03-31,0.000000,278.29999,164164.0,23.023424,4.568684e+07
4098031,93436,2017-04-30,0.000000,314.07001,164260.0,24.373707,5.158914e+07
4098032,93436,2017-05-31,0.000000,341.01001,164260.0,27.942659,5.601430e+07
4098033,93436,2017-06-30,0.000000,361.60999,166863.0,33.011217,6.033933e+07
4098034,93436,2017-07-31,0.000000,323.47000,166887.0,39.067422,5.398294e+07
4098035,93436,2017-08-31,0.000000,355.89999,166887.0,41.425934,5.939508e+07
4098036,93436,2017-09-30,0.000000,341.10001,168017.0,45.341310,5.731060e+07
4098037,93436,2017-10-31,0.000000,331.53000,168067.0,48.118293,5.571925e+07
4098038,93436,2017-11-30,0.000000,308.85001,168067.0,50.128638,5.190749e+07
4098039,93436,2017-12-31,0.000000,311.35001,168797.0,51.099733,5.255495e+07
4098040,93436,2018-01-31,0.000000,354.31000,168797.0,51.847135,5.980647e+07
4098041,93436,2018-02-28,0.000000,343.06000,168920.0,53.774889,5.794970e+07
4098042,93436,2018-03-31,0.000000,266.13000,169750.0,54.813517,4.517557e+07
4098043,93436,2018-04-30,0.000000,293.89999,169794.0,53.454523,4.990245e+07
4098044,93436,2018-05-31,0.000000,284.73001,169794.0,53.322950,4.834545e+07
4098045,93436,2018-06-30,0.000000,342.95001,170516.0,53.369757,5.847846e+07

In [4]:
data['date'] = data['date'].apply(lambda x:datetime.datetime.strptime(x,'%Y-%m-%d'))

In [5]:
# Filter data, get when are the dates used
head, mid, tail = [], [], []
for i1 in range(1964, 2018):
    for i2 in range(2,13):
        mid.append(datetime.datetime(i1, i2, 1)-datetime.timedelta(days = 1))
    mid.append(datetime.datetime(i1+1, 1, 1)-datetime.timedelta(days = 1))

for i1 in range(8, 13):
    head.append(datetime.datetime(1963, i1, 1)-datetime.timedelta(days = 1))
head.append(datetime.datetime(1964, 1, 1)-datetime.timedelta(days = 1))
    
for i1 in range(2, 8):
    tail.append(datetime.datetime(2018,i1,1)-datetime.timedelta(days = 1))

dates_month = head+mid+tail # The index of the data file, in months

In [6]:
# Record dates
cur_tic = data['PERMNO'][0]
start_ind = 0
dates_ind = {}
dates = {}
start_time = time.time()

def strtodatetime(string):
    datetime.strptime(string)

for i in range(len(data)):
    if data['PERMNO'][i]==cur_tic:
        pass
    else:
        dates_ind.update({cur_tic:[start_ind, i-1]})
        dates.update({cur_tic:[data['date'][start_ind],data['date'][i-1]]})
        start_ind=i
        cur_tic = data['PERMNO'][i]
        
dates_ind.update({cur_tic:[start_ind, i]})
dates.update({cur_tic:[data['date'][start_ind],data['date'][i]]})
print(time.time()-start_time)

144.89897203445435

In [11]:
# For some stocks, the shares outstanding and the prices may be missing, 
# if so we need to mark the date when they have both price and shares outstanding
volnan = data['Rolling 36m Vol'].isnull() # True for vol is NaN
pop_lst = []

for ticker in dates_ind:
    # Get the start right
    si, ei = dates_ind[ticker][0], dates_ind[ticker][1]
    if volnan[si] and volnan[ei]:
        pop_lst.append(ticker)
        continue
    while(data['PRC'].iloc[si]<0 or data['SHROUT'].iloc[si]<0 or volnan[si]):
        si+=1
    while(data['PRC'].iloc[ei]<0 or data['SHROUT'].iloc[ei]<0 or volnan[ei]):
        ei-=1
    dates_ind.update({ticker:[si,ei]})
    dates.update({ticker:[data['date'][si],data['date'][ei]]})
    
for ticker in pop_lst:
    dates_ind.pop(ticker)
    dates.pop(ticker)
print('Run time: %.2f s. Remained Stocks: %d'%(time.time()-start_time,len(dates_ind)))

392.32103633880615

In [14]:
# Get 12m momentum
# Given that all the stocks here have at least 36m of price, you can easily get their 12m momentum without filtering
momentum_lst = [np.nan]*len(data)
for ticker in dates_ind:
    si, ei = dates_ind[ticker][0], dates_ind[ticker][1]
    for i in range(si,ei+1):
        momentum_lst[i] = (data['PRC'][i]-data['PRC'][i-12])/data['PRC'][i-12]
data['12m Mom'] = momentum_lst        
data

,PERMNO,date,DIVAMT,PRC,SHROUT,Rolling 36m Vol,Mkt Cap,12m Mom
0,10000,1985-12-31,0.000000,-1.00000,-1.0,NaN,1.000000e+00,NaN
1,10000,1986-01-31,0.000000,4.37500,3680.0,NaN,1.610000e+04,NaN
2,10000,1986-02-28,0.000000,3.25000,3680.0,NaN,1.196000e+04,NaN
3,10000,1986-03-31,0.000000,4.43750,3680.0,NaN,1.633000e+04,NaN
4,10000,1986-04-30,0.000000,4.00000,3793.0,NaN,1.517200e+04,NaN
5,10000,1986-05-31,0.000000,3.10938,3793.0,NaN,1.179388e+04,NaN
6,10000,1986-06-30,0.000000,3.09375,3793.0,NaN,1.173459e+04,NaN
7,10000,1986-07-31,0.000000,2.84375,3793.0,NaN,1.078634e+04,NaN
8,10000,1986-08-31,0.000000,1.09375,3793.0,NaN,4.148594e+03,NaN
9,10000,1986-09-30,0.000000,1.03125,3793.0,NaN,3.911531e+03,NaN
10,10000,1986-10-31,0.000000,0.78125,3843.0,NaN,3.002344e+03,NaN
11,10000,1986-11-30,0.000000,0.82813,3843.0,NaN,3.182504e+03,NaN
12,10000,1986-12-31,0.000000,0.51563,3843.0,NaN,1.981566e+03,NaN
13,10000,1987-01-31,0.000000,0.40625,3893.0,NaN,1.581531e+03,NaN
14,10000,1987-02-28,0.000000,0.40625,3893.0,NaN,1.581531e+03,NaN
15,10000,1987-03-31,0.000000,0.25000,3893.0,NaN,9.732500e+02,NaN
16,10000,1987-04-30,0.000000,0.23438,3893.0,NaN,9.124413e+02,NaN
17,10000,1987-05-31,0.000000,0.21875,3893.0,NaN,8.515938e+02,NaN
18,10000,1987-06-30,0.000000,-1.00000,3893.0,NaN,-3.893000e+03,NaN
19,10001,1985-12-31,0.000000,-1.00000,-1.0,NaN,1.000000e+00,NaN
20,10001,1986-01-31,0.000000,6.12500,985.0,NaN,6.033125e+03,NaN
21,10001,1986-02-28,0.000000,6.25000,985.0,NaN,6.156250e+03,NaN
22,10001,1986-03-31,0.031667,6.31250,985.0,NaN,6.217812e+03,NaN
23,10001,1986-04-30,0.031667,6.37500,985.0,NaN,6.279375e+03,NaN
24,10001,1986-05-31,0.031667,6.31250,985.0,NaN,6.217812e+03,NaN
25,10001,1986-06-30,0.035000,6.12500,985.0,NaN,6.033125e+03,NaN
26,10001,1986-07-31,0.035000,6.06250,985.0,NaN,5.971562e+03,NaN
27,10001,1986-08-31,0.035000,6.50000,985.0,NaN,6.402500e+03,NaN
28,10001,1986-09-30,0.035000,6.37500,991.0,NaN,6.317625e+03,NaN
29,10001,1986-10-31,0.035000,6.62500,991.0,NaN,6.565375e+03,NaN
...,...,...,...,...,...,...,...,...
4098016,93436,2016-01-31,0.000000,191.20000,132056.0,67.974093,2.524911e+07,-0.060904
4098017,93436,2016-02-29,0.000000,191.92999,132056.0,62.937431,2.534551e+07,-0.056113
4098018,93436,2016-03-31,0.000000,229.77000,133858.0,56.929345,3.075655e+07,0.217196
4098019,93436,2016-04-30,0.000000,240.75999,133945.0,50.275961,3.224860e+07,0.065074
4098020,93436,2016-05-31,0.000000,223.23000,147543.0,43.810568,3.293602e+07,-0.109928
4098021,93436,2016-06-30,0.000000,212.28000,148015.0,39.647662,3.142062e+07,-0.208678
4098022,93436,2016-07-31,0.000000,234.78999,148693.0,35.479931,3.491163e+07,-0.117828
4098023,93436,2016-08-31,0.000000,212.00999,149239.0,32.877783,3.164016e+07,-0.148759
4098024,93436,2016-09-30,0.000000,204.03000,149825.0,31.848610,3.056879e+07,-0.178623
4098025,93436,2016-10-31,0.000000,197.73000,149891.0,31.658101,2.963795e+07,-0.044459
4098026,93436,2016-11-30,0.000000,189.39999,149964.0,30.269247,2.840318e+07,-0.177452
4098027,93436,2016-12-31,0.000000,213.69000,161561.0,26.444773,3.452397e+07,-0.109662
4098028,93436,2017-01-31,0.000000,251.92999,161670.0,23.572926,4.072952e+07,0.317625
4098029,93436,2017-02-28,0.000000,249.99001,161670.0,22.888288,4.041588e+07,0.302506
4098030,93436,2017-03-31,0.000000,278.29999,164164.0,23.023424,4.568684e+07,0.211211
4098031,93436,2017-04-30,0.000000,314.07001,164260.0,24.373707,5.158914e+07,0.304494
4098032,93436,2017-05-31,0.000000,341.01001,164260.0,27.942659,5.601430e+07,0.527617
4098033,93436,2017-06-30,0.000000,361.60999,166863.0,33.011217,6.033933e+07,0.703458
4098034,93436,2017-07-31,0.000000,323.47000,166887.0,39.067422,5.398294e+07,0.377699
4098035,93436,2017-08-31,0.000000,355.89999,166887.0,41.425934,5.939508e+07,0.678694
4098036,93436,2017-09-30,0.000000,341.10001,168017.0,45.341310,5.731060e+07,0.671813
4098037,93436,2017-10-31,0.000000,331.53000,168067.0,48.118293,5.571925e+07,0.676680
4098038,93436,2017-11-30,0.000000,308.85001,168067.0,50.128638,5.190749e+07,0.630676
4098039,93436,2017-12-31,0.000000,311.35001,168797.0,51.099733,5.255495e+07,0.457017
4098040,93436,2018-01-31,0.000000,354.31000,168797.0,51.847135,5.980647e+07,0.406383
4098041,93436,2018-02-28,0.000000,343.06000,168920.0,53.774889,5.794970e+07,0.372295
4098042,93436,2018-03-31,0.000000,266.13000,169750.0,54.813517,4.517557e+07,-0.043730
4098043,93436,2018-04-30,0.000000,293.89999,169794.0,53.454523,4.990245e+07,-0.064221
4098044,93436,2018-05-31,0.000000,284.73001,169794.0,53.322950,4.834545e+07,-0.165039
4098045,93436,2018-06-30,0.000000,342.95001,170516.0,53.369757,5.847846e+07,-0.051603

In [15]:
data.to_csv('data_12mom_36vol_div.csv')

In [ ]:
start_time = time.time()
stock_components = {}

# find_stocks will save the tickers of the stocks available at given date and return a list of them
def find_stocks(target_date):
    stock_lst = []
    for ticker in dates:
        if dates[ticker][0] <= target_date and dates[ticker][1] >= target_date:
            stock_lst.append(ticker)
    return stock_lst


for i in dates_month:
    stock_components.update({i:find_stocks(i)})
    
print(time.time()-start_time)

In [ ]:
# Find the components of the portfolio for a given date 
def find_component(date,
                  start_time):
    date_df = []
    for stock in stock_components[date]:
        data_slice = pd.DataFrame(data[dates_ind[stock][0]:dates_ind[stock][1]+1])
        n = np.where(data_slice['date']==date)
        date_df.append(data_slice.iloc[n])
    print(time.time()-start_time)
    return pd.concat(date_df)

frame = find_component(datetime.datetime(2018, 6, 30, 0, 0), time.time())

In [ ]:
frame = frame.sort_values(by=['Mkt Cap'],ascending=False)[0:1000]
frame

In [ ]:
dates_month

In [10]:
# Pick low-vol decile
# The rebalancing happens every quarter
# Take the 1000 most liquid stocks. Rank the 500 most low-vol stocks
# Give scores based on 12m momentum and income (dividend), The higher they are the better

def 

def form_portfolio():
    for month in dates_month:
        frame = find_component(month, time.time()).sort_values(by=['Mkt Cap'],ascending=False)
        
    
def process_strat():
    pass

KeyError: ''

In [ ]:
class Stock(object):
    def __init__(self, ticker, buy_price, enter_time):
        self.ticker = ticker
        self.enter_price = buy_price
        self.price_seq = [buy_price]
        self.enter_time = enter_time