In [1]:
import pandas as pd
import numpy as np
import datetime
import time

In [18]:
data = pd.read_csv('with_vols.csv', low_memory=False, index_col=0)
data

D:\Anaconda3\lib\site-packages\numpy\lib\arraysetops.py:569: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)

         PERMNO        date    DIVAMT        PRC    SHROUT  Rolling 12m Vol
0         10000  1985-12-31  0.000000   -1.00000      -1.0              NaN
1         10000  1986-01-31  0.000000    4.37500    3680.0              NaN
2         10000  1986-02-28  0.000000    3.25000    3680.0              NaN
3         10000  1986-03-31  0.000000    4.43750    3680.0              NaN
4         10000  1986-04-30  0.000000    4.00000    3793.0              NaN
5         10000  1986-05-31  0.000000    3.10938    3793.0              NaN
6         10000  1986-06-30  0.000000    3.09375    3793.0              NaN
7         10000  1986-07-31  0.000000    2.84375    3793.0              NaN
8         10000  1986-08-31  0.000000    1.09375    3793.0              NaN
9         10000  1986-09-30  0.000000    1.03125    3793.0              NaN
10        10000  1986-10-31  0.000000    0.78125    3843.0              NaN
11        10000  1986-11-30  0.000000    0.82813    3843.0              NaN
12        10000  1986-12-31  0.000000    0.51563    3843.0              NaN
13        10000  1987-01-31  0.000000    0.40625    3893.0         1.435027
14        10000  1987-02-28  0.000000    0.40625    3893.0         1.409594
15        10000  1987-03-31  0.000000    0.25000    3893.0         1.437770
16        10000  1987-04-30  0.000000    0.23438    3893.0         1.273181
17        10000  1987-05-31  0.000000    0.21875    3893.0         1.074227
18        10000  1987-06-30  0.000000   -1.00000    3893.0              NaN
19        10001  1985-12-31  0.000000   -1.00000      -1.0              NaN
20        10001  1986-01-31  0.000000    6.12500     985.0              NaN
21        10001  1986-02-28  0.000000    6.25000     985.0              NaN
22        10001  1986-03-31  0.031667    6.31250     985.0              NaN
23        10001  1986-04-30  0.031667    6.37500     985.0              NaN
24        10001  1986-05-31  0.031667    6.31250     985.0              NaN
25        10001  1986-06-30  0.035000    6.12500     985.0              NaN
26        10001  1986-07-31  0.035000    6.06250     985.0              NaN
27        10001  1986-08-31  0.035000    6.50000     985.0              NaN
28        10001  1986-09-30  0.035000    6.37500     991.0              NaN
29        10001  1986-10-31  0.035000    6.62500     991.0              NaN
...         ...         ...       ...        ...       ...              ...
4098016   93436  2016-01-31  0.000000  191.20000  132056.0        25.202296
4098017   93436  2016-02-29  0.000000  191.92999  132056.0        26.555348
4098018   93436  2016-03-31  0.000000  229.77000  133858.0        27.700047
4098019   93436  2016-04-30  0.000000  240.75999  133945.0        24.803335
4098020   93436  2016-05-31  0.000000  223.23000  147543.0        24.781435
4098021   93436  2016-06-30  0.000000  212.28000  148015.0        24.435724
4098022   93436  2016-07-31  0.000000  234.78999  148693.0        22.354128
4098023   93436  2016-08-31  0.000000  212.00999  149239.0        19.308349
4098024   93436  2016-09-30  0.000000  204.03000  149825.0        18.121559
4098025   93436  2016-10-31  0.000000  197.73000  149891.0        16.794403
4098026   93436  2016-11-30  0.000000  189.39999  149964.0        17.482701
4098027   93436  2016-12-31  0.000000  213.69000  161561.0        18.578174
4098028   93436  2017-01-31  0.000000  251.92999  161670.0        16.842055
4098029   93436  2017-02-28  0.000000  249.99001  161670.0        18.908695
4098030   93436  2017-03-31  0.000000  278.29999  164164.0        19.350054
4098031   93436  2017-04-30  0.000000  314.07001  164260.0        24.902570
4098032   93436  2017-05-31  0.000000  341.01001  164260.0        34.856163
4098033   93436  2017-06-30  0.000000  361.60999  166863.0        45.898203
4098034   93436  2017-07-31  0.000000  323.47000  166887.0        55.500332
4098035   93436  2017-08-31  0.000000  355.89999  166887.0        58.278696
4098036   93436  2017-09-30  0.000000  341.10001  168017.0        61.584522
4098037   93436  2017-10-31  0.000000  331.53000  168067.0        60.352930
4098038   93436  2017-11-30  0.000000  308.85001  168067.0        55.382738
4098039   93436  2017-12-31  0.000000  311.35001  168797.0        45.110519
4098040   93436  2018-01-31  0.000000  354.31000  168797.0        35.521304
4098041   93436  2018-02-28  0.000000  343.06000  168920.0        31.650373
4098042   93436  2018-03-31  0.000000  266.13000  169750.0        23.167902
4098043   93436  2018-04-30  0.000000  293.89999  169794.0        25.567578
4098044   93436  2018-05-31  0.000000  284.73001  169794.0        27.132966
4098045   93436  2018-06-30  0.000000  342.95001  170516.0        29.209012

[4098046 rows x 6 columns]

In [27]:
data['date'] = data['date'].apply(lambda x:datetime.datetime.strptime(x,'%Y-%m-%d'))

In [31]:
# Filter data, get when are the dates used
head, mid, tail = [], [], []
for i1 in range(1964, 2018):
    for i2 in range(2,13):
        mid.append(datetime.datetime(i1, i2, 1)-datetime.timedelta(days = 1))
    mid.append(datetime.datetime(i1+1, 1, 1)-datetime.timedelta(days = 1))

for i1 in range(8, 13):
    head.append(datetime.datetime(1963, i1, 1)-datetime.timedelta(days = 1))
head.append(datetime.datetime(1964, 1, 1)-datetime.timedelta(days = 1))
    
for i1 in range(2, 8):
    tail.append(datetime.datetime(2018,i1,1)-datetime.timedelta(days = 1))

dates_month = head+mid+tail # The index of the data file, in months

In [32]:
# Record dates
cur_tic = data['PERMNO'][0]
start_ind = 0
dates_ind = {}
dates = {}
start_time = time.time()

def strtodatetime(string):
    datetime.strptime(string)

for i in range(len(data)):
    if data['PERMNO'][i]==cur_tic:
        pass
    else:
        dates_ind.update({cur_tic:[start_ind, i-1]})
        dates.update({cur_tic:[data['date'][start_ind],data['date'][i-1]]})
        start_ind=i
        cur_tic = data['PERMNO'][i]
        
dates_ind.update({cur_tic:[start_ind, i]})
dates.update({cur_tic:[data['date'][start_ind],data['date'][i]]})
print(time.time()-start_time)

# For some stocks, the shares outstanding and the prices may be missing, 
# if so we need to mark the date when they have both price and shares outstanding
volnan = data['Rolling 12m Vol'].isnull() # True for vol is NaN

for ticker in dates_ind:
    # Get the start right
    si, ei = dates_ind[ticker][0], dates_ind[ticker][1]
    while(data['PRC'].iloc[si]<0 or data['SHROUT'].iloc[si]<0 or volnan[si]):
        si+=1
    while(data['PRC'].iloc[ei]<0 or data['SHROUT'].iloc[ei]<0 or volnan[ei]):
        ei-=1
    dates_ind.update({ticker:[si,ei]})
    dates.update({ticker:[data['date'][si],data['date'][ei]]})
print(time.time()-start_time)

124.94350361824036
166.92874002456665

In [34]:
dates

{10000: [Timestamp('1987-01-31 00:00:00'), Timestamp('1987-05-31 00:00:00')],
 10001: [Timestamp('1987-01-31 00:00:00'), Timestamp('2017-07-31 00:00:00')],
 10002: [Timestamp('1987-01-31 00:00:00'), Timestamp('2013-01-31 00:00:00')],
 10003: [Timestamp('1987-01-31 00:00:00'), Timestamp('1995-11-30 00:00:00')],
 10005: [Timestamp('1987-01-31 00:00:00'), Timestamp('1991-06-30 00:00:00')],
 10006: [Timestamp('1964-07-31 00:00:00'), Timestamp('1984-05-31 00:00:00')],
 10007: [Timestamp('1987-01-31 00:00:00'), Timestamp('1990-09-30 00:00:00')],
 10008: [Timestamp('1987-01-31 00:00:00'), Timestamp('1988-10-31 00:00:00')],
 10009: [Timestamp('1987-01-31 00:00:00'), Timestamp('2000-10-31 00:00:00')],
 10010: [Timestamp('1987-01-31 00:00:00'), Timestamp('1995-07-31 00:00:00')],
 10011: [Timestamp('1989-06-30 00:00:00'), Timestamp('1998-01-31 00:00:00')],
 10012: [Timestamp('1987-01-31 00:00:00'), Timestamp('2005-07-31 00:00:00')],
 10013: [Timestamp('1987-01-31 00:00:00'), Timestamp('1987-02-28 00:00:00')],
 10014: [Timestamp('1964-07-31 00:00:00'), Timestamp('1977-03-31 00:00:00')],
 10015: [Timestamp('1984-09-30 00:00:00'), Timestamp('1986-06-30 00:00:00')],
 10016: [Timestamp('1987-01-31 00:00:00'), Timestamp('2001-04-30 00:00:00')],
 10017: [Timestamp('1987-01-31 00:00:00'), Timestamp('1988-08-31 00:00:00')],
 10018: [Timestamp('1987-01-31 00:00:00'), Timestamp('1995-10-31 00:00:00')],
 10019: [Timestamp('1987-01-31 00:00:00'), Timestamp('2002-05-31 00:00:00')],
 10020: [Timestamp('1986-12-31 00:00:00'), Timestamp('1993-04-30 00:00:00')],
 10021: [Timestamp('1987-01-31 00:00:00'), Timestamp('1995-12-31 00:00:00')],
 10023: [Timestamp('1987-01-31 00:00:00'), Timestamp('1995-12-31 00:00:00')],
 10024: [Timestamp('1987-01-31 00:00:00'), Timestamp('1992-04-30 00:00:00')],
 10025: [Timestamp('1987-01-31 00:00:00'), Timestamp('2016-12-31 00:00:00')],
 10026: [Timestamp('1987-02-28 00:00:00'), Timestamp('2018-06-30 00:00:00')],
 10027: [Timestamp('1987-02-28 00:00:00'), Timestamp('1990-02-28 00:00:00')],
 10028: [Timestamp('1987-02-28 00:00:00'), Timestamp('2018-06-30 00:00:00')],
 10029: [Timestamp('1987-02-28 00:00:00'), Timestamp('1990-07-31 00:00:00')],
 10030: [Timestamp('1964-07-31 00:00:00'), Timestamp('1968-11-30 00:00:00')],
 10031: [Timestamp('1984-12-31 00:00:00'), Timestamp('1989-07-31 00:00:00')],
 10032: [Timestamp('1987-02-28 00:00:00'), Timestamp('2018-06-30 00:00:00')],
 10033: [Timestamp('1987-02-28 00:00:00'), Timestamp('2018-06-30 00:00:00')],
 10034: [Timestamp('1987-02-28 00:00:00'), Timestamp('1991-08-31 00:00:00')],
 10035: [Timestamp('1987-02-28 00:00:00'), Timestamp('2003-11-30 00:00:00')],
 10036: [Timestamp('1987-02-28 00:00:00'), Timestamp('1991-02-28 00:00:00')],
 10037: [Timestamp('1987-02-28 00:00:00'), Timestamp('2004-05-31 00:00:00')],
 10038: [Timestamp('1987-02-28 00:00:00'), Timestamp('1990-12-31 00:00:00')],
 10039: [Timestamp('1987-02-28 00:00:00'), Timestamp('2001-05-31 00:00:00')],
 10040: [Timestamp('1987-02-28 00:00:00'), Timestamp('1989-05-31 00:00:00')],
 10041: [Timestamp('1987-02-28 00:00:00'), Timestamp('1990-04-30 00:00:00')],
 10042: [Timestamp('1987-02-28 00:00:00'), Timestamp('2008-02-29 00:00:00')],
 10043: [Timestamp('1987-02-28 00:00:00'), Timestamp('1999-05-31 00:00:00')],
 10044: [Timestamp('1987-02-28 00:00:00'), Timestamp('2018-06-30 00:00:00')],
 10045: [Timestamp('1987-02-28 00:00:00'), Timestamp('1987-03-31 00:00:00')],
 10046: [Timestamp('1987-02-28 00:00:00'), Timestamp('1995-02-28 00:00:00')],
 10047: [Timestamp('1987-02-28 00:00:00'), Timestamp('1994-12-31 00:00:00')],
 10048: [Timestamp('1987-02-28 00:00:00'), Timestamp('1999-09-30 00:00:00')],
 10050: [Timestamp('1973-12-31 00:00:00'), Timestamp('1978-05-31 00:00:00')],
 10051: [Timestamp('1987-02-28 00:00:00'), Timestamp('2016-01-31 00:00:00')],
 10052: [Timestamp('1987-02-28 00:00:00'), Timestamp('1988-02-29 00:00:00')],
 10053: [Timestamp('1987-02-28 00:00:00'), Timestamp('1989-12-31 00:00:00')],
 10054: [Timestamp('1987-02-28 00:00:00'), Timestamp('1989-12-31 00:00:00')],
 10055: [Timestamp('1987-02-28 00:00:00'), Timestamp('1995-07-31 00:00:00')],
 10056: [Timestamp('1987-02-28 00:00:00'), Timestamp('2006-09-30 00:00:00')],
 10057: [Timestamp('1964-07-31 00:00:00'), Timestamp('1996-06-30 00:00:00')],
 10058: [Timestamp('1973-11-30 00:00:00'), Timestamp('1984-08-31 00:00:00')],
 10059: [Timestamp('1987-02-28 00:00:00'), Timestamp('1994-03-31 00:00:00')],
 10060: [Timestamp('1987-02-28 00:00:00'), Timestamp('1998-05-31 00:00:00')],
 10061: [Timestamp('1987-02-28 00:00:00'), Timestamp('1990-06-30 00:00:00')],
 10062: [Timestamp('1987-02-28 00:00:00'), Timestamp('1999-08-31 00:00:00')],
 10063: [Timestamp('1987-02-28 00:00:00'), Timestamp('1993-06-30 00:00:00')],
 10064: [Timestamp('1987-02-28 00:00:00'), Timestamp('1997-02-28 00:00:00')],
 10065: [Timestamp('1964-06-30 00:00:00'), Timestamp('2018-06-30 00:00:00')],
 10066: [Timestamp('1984-08-31 00:00:00'), Timestamp('2002-07-31 00:00:00')],
 10067: [Timestamp('1987-02-28 00:00:00'), Timestamp('2002-07-31 00:00:00')],
 10068: [Timestamp('1987-02-28 00:00:00'), Timestamp('2002-07-31 00:00:00')],
 10069: [Timestamp('1987-02-28 00:00:00'), Timestamp('2002-07-31 00:00:00')],
 10070: [Timestamp('1987-02-28 00:00:00'), Timestamp('1990-10-31 00:00:00')],
 10071: [Timestamp('1987-01-31 00:00:00'), Timestamp('1997-08-31 00:00:00')],
 10072: [Timestamp('1987-02-28 00:00:00'), Timestamp('1992-09-30 00:00:00')],
 10074: [Timestamp('1983-01-31 00:00:00'), Timestamp('1996-02-29 00:00:00')],
 10075: [Timestamp('1987-03-31 00:00:00'), Timestamp('1999-06-30 00:00:00')],
 10076: [Timestamp('1987-03-31 00:00:00'), Timestamp('1990-05-31 00:00:00')],
 10077: [Timestamp('1987-04-30 00:00:00'), Timestamp('1993-12-31 00:00:00')],
 10078: [Timestamp('1987-03-31 00:00:00'), Timestamp('2009-12-31 00:00:00')],
 10079: [Timestamp('1987-03-31 00:00:00'), Timestamp('1995-02-28 00:00:00')],
 10080: [Timestamp('1987-03-31 00:00:00'), Timestamp('2003-10-31 00:00:00')],
 10082: [Timestamp('1984-03-31 00:00:00'), Timestamp('1995-08-31 00:00:00')],
 10083: [Timestamp('1987-03-31 00:00:00'), Timestamp('1993-08-31 00:00:00')],
 10084: [Timestamp('1987-03-31 00:00:00'), Timestamp('1994-02-28 00:00:00')],
 10085: [Timestamp('1987-03-31 00:00:00'), Timestamp('2006-03-31 00:00:00')],
 10086: [Timestamp('1987-03-31 00:00:00'), Timestamp('1994-06-30 00:00:00')],
 10087: [Timestamp('1987-03-31 00:00:00'), Timestamp('2000-09-30 00:00:00')],
 10088: [Timestamp('1987-03-31 00:00:00'), Timestamp('1988-04-30 00:00:00')],
 10089: [Timestamp('1987-03-31 00:00:00'), Timestamp('2005-02-28 00:00:00')],
 10090: [Timestamp('1987-03-31 00:00:00'), Timestamp('1995-07-31 00:00:00')],
 10091: [Timestamp('1987-03-31 00:00:00'), Timestamp('1989-01-31 00:00:00')],
 10092: [Timestamp('1987-03-31 00:00:00'), Timestamp('2010-05-31 00:00:00')],
 10093: [Timestamp('1987-03-31 00:00:00'), Timestamp('1990-04-30 00:00:00')],
 10094: [Timestamp('1987-03-31 00:00:00'), Timestamp('1997-11-30 00:00:00')],
 10095: [Timestamp('1987-03-31 00:00:00'), Timestamp('1994-11-30 00:00:00')],
 10096: [Timestamp('1987-03-31 00:00:00'), Timestamp('1990-02-28 00:00:00')],
 10097: [Timestamp('1987-03-31 00:00:00'), Timestamp('1996-03-31 00:00:00')],
 10098: [Timestamp('1987-03-31 00:00:00'), Timestamp('1989-03-31 00:00:00')],
 10099: [Timestamp('1987-03-31 00:00:00'), Timestamp('1987-06-30 00:00:00')],
 10100: [Timestamp('1987-03-31 00:00:00'), Timestamp('2013-02-28 00:00:00')],
 10101: [Timestamp('1987-03-31 00:00:00'), Timestamp('1988-06-30 00:00:00')],
 10102: [Timestamp('1964-07-31 00:00:00'), Timestamp('1978-04-30 00:00:00')],
 10103: [Timestamp('1978-03-31 00:00:00'), Timestamp('1989-11-30 00:00:00')],
 10104: [Timestamp('1987-03-31 00:00:00'), Timestamp('2018-06-30 00:00:00')],
 10105: [Timestamp('1987-03-31 00:00:00'), Timestamp('1987-07-31 00:00:00')],
 10106: [Timestamp('1987-03-31 00:00:00'), Timestamp('1994-12-31 00:00:00')],
 10107: [Timestamp('1987-03-31 00:00:00'), Timestamp('2018-06-30 00:00:00')],
 10108: [Timestamp('1987-03-31 00:00:00'), Timestamp('2005-07-31 00:00:00')],
 10109: [Timestamp('1987-01-31 00:00:00'), Timestamp('1990-07-31 00:00:00')],
 10111: [Timestamp('1987-03-31 00:00:00'), Timestamp('1990-07-31 00:00:00')],
 10112: [Timestamp('1987-03-31 00:00:00'), Timestamp('1988-05-31 00:00:00')],
 10113: [Timestamp('2011-07-31 00:00:00'), Timestamp('2018-06-30 00:00:00')],
 10114: [Timestamp('1989-06-30 00:00:00'), Timestamp('2004-07-31 00:00:00')],
 10115: [Timestamp('1987-03-31 00:00:00'), Timestamp('1988-05-31 00:00:00')],
 10116: [Timestamp('1987-03-31 00:00:00'), Timestamp('2017-01-31 00:00:00')],
 10117: [Timestamp('1987-03-31 00:00:00'), Timestamp('1987-09-30 00:00:00')],
 10118: [Timestamp('1987-03-31 00:00:00'), Timestamp('1988-10-31 00:00:00')],
 10119: [Timestamp('1987-03-31 00:00:00'), Timestamp('2007-08-31 00:00:00')],
 10120: [Timestamp('1987-03-31 00:00:00'), Timestamp('1998-04-30 00:00:00')],
 10121: [Timestamp('1987-03-31 00:00:00'), Timestamp('1991-12-31 00:00:00')],
 10122: [Timestamp('1987-03-31 00:00:00'), Timestamp('2002-09-30 00:00:00')],
 10123: [Timestamp('1989-04-30 00:00:00'), Timestamp('2002-05-31 00:00:00')],
 10124: [Timestamp('1987-03-31 00:00:00'), Timestamp('1987-11-30 00:00:00')],
 10125: [Timestamp('1987-03-31 00:00:00'), Timestamp('1991-08-31 00:00:00')],
 10126: [Timestamp('1987-02-28 00:00:00'), Timestamp('2000-06-30 00:00:00')],
 10127: [Timestamp('1987-03-31 00:00:00'), Timestamp('2002-03-31 00:00:00')],
 10128: [Timestamp('1994-01-31 00:00:00'), Timestamp('2001-01-31 00:00:00')],
 10130: [Timestamp('1987-03-31 00:00:00'), Timestamp('1999-06-30 00:00:00')],
 10131: [Timestamp('1987-03-31 00:00:00'), Timestamp('1991-08-31 00:00:00')],
 10132: [Timestamp('1987-03-31 00:00:00'), Timestamp('1989-10-31 00:00:00')],
 10133: [Timestamp('1987-03-31 00:00:00'), Timestamp('1990-09-30 00:00:00')],
 10134: [Timestamp('1987-04-30 00:00:00'), Timestamp('1988-10-31 00:00:00')],
 10135: [Timestamp('1987-04-30 00:00:00'), Timestamp('1989-01-31 00:00:00')],
 10136: [Timestamp('1987-04-30 00:00:00'), Timestamp('1996-02-29 00:00:00')],
 10137: [Timestamp('1964-06-30 00:00:00'), Timestamp('2011-01-31 00:00:00')],
 10138: [Timestamp('1987-04-30 00:00:00'), Timestamp('2018-06-30 00:00:00')],
 10139: [Timestamp('1989-06-30 00:00:00'), Timestamp('1989-08-31 00:00:00')],
 10140: [Timestamp('1987-04-30 00:00:00'), Timestamp('1998-06-30 00:00:00')],
 10141: [Timestamp('1987-04-30 00:00:00'), Timestamp('1996-06-30 00:00:00')],
 10142: [Timestamp('1987-04-30 00:00:00'), Timestamp('2000-03-31 00:00:00')],
 10143: [Timestamp('1987-04-30 00:00:00'), Timestamp('2010-05-31 00:00:00')],
 10144: [Timestamp('1987-04-30 00:00:00'), Timestamp('1988-08-31 00:00:00')],
 10145: [Timestamp('1964-07-31 00:00:00'), Timestamp('2018-06-30 00:00:00')],
 10146: [Timestamp('1973-12-31 00:00:00'), Timestamp('1988-03-31 00:00:00')],
 10147: [Timestamp('1987-04-30 00:00:00'), Timestamp('2016-08-31 00:00:00')],
 10148: [Timestamp('1987-04-30 00:00:00'), Timestamp('1991-03-31 00:00:00')],
 10149: [Timestamp('1987-04-30 00:00:00'), Timestamp('2002-06-30 00:00:00')],
 10150: [Timestamp('1987-04-30 00:00:00'), Timestamp('1998-01-31 00:00:00')],
 10151: [Timestamp('2011-07-31 00:00:00'), Timestamp('2015-07-31 00:00:00')],
 10152: [Timestamp('1987-04-30 00:00:00'), Timestamp('1990-04-30 00:00:00')],
 10153: [Timestamp('1964-07-31 00:00:00'), Timestamp('1988-11-30 00:00:00')],
 10154: [Timestamp('1973-12-31 00:00:00'), Timestamp('1996-01-31 00:00:00')],
 10155: [Timestamp('1987-04-30 00:00:00'), Timestamp('2001-05-31 00:00:00')],
 10156: [Timestamp('1987-04-30 00:00:00'), Timestamp('1991-03-31 00:00:00')],
 10157: [Timestamp('1987-04-30 00:00:00'), Timestamp('1996-12-31 00:00:00')],
 10158: [Timestamp('2011-07-31 00:00:00'), Timestamp('2018-06-30 00:00:00')],
 10159: [Timestamp('1987-04-30 00:00:00'), Timestamp('1990-05-31 00:00:00')],
 10160: [Timestamp('1987-04-30 00:00:00'), Timestamp('2003-05-31 00:00:00')],
 10161: [Timestamp('1964-07-31 00:00:00'), Timestamp('1993-10-31 00:00:00')],
 10162: [Timestamp('1974-01-31 00:00:00'), Timestamp('1981-02-28 00:00:00')],
 10163: [Timestamp('1987-04-30 00:00:00'), Timestamp('2012-04-30 00:00:00')],
 10164: [Timestamp('1987-04-30 00:00:00'), Timestamp('1989-08-31 00:00:00')],
 10165: [Timestamp('1987-04-30 00:00:00'), Timestamp('1988-01-31 00:00:00')],
 10166: [Timestamp('1987-04-30 00:00:00'), Timestamp('1992-09-30 00:00:00')],
 10167: [Timestamp('1987-04-30 00:00:00'), Timestamp('1987-05-31 00:00:00')],
 10168: [Timestamp('1987-04-30 00:00:00'), Timestamp('1989-03-31 00:00:00')],
 10169: [Timestamp('1987-04-30 00:00:00'), Timestamp('1987-08-31 00:00:00')],
 10170: [Timestamp('1987-04-30 00:00:00'), Timestamp('2003-04-30 00:00:00')],
 10171: [Timestamp('1987-04-30 00:00:00'), Timestamp('1990-04-30 00:00:00')],
 10172: [Timestamp('1987-04-30 00:00:00'), Timestamp('1991-11-30 00:00:00')],
 10173: [Timestamp('1987-04-30 00:00:00'), Timestamp('1996-01-31 00:00:00')],
 10174: [Timestamp('1987-03-31 00:00:00'), Timestamp('1993-02-28 00:00:00')],
 10175: [Timestamp('1987-04-30 00:00:00'), Timestamp('1997-06-30 00:00:00')],
 10176: [Timestamp('1987-04-30 00:00:00'), Timestamp('1992-05-31 00:00:00')],
 10177: [Timestamp('1987-04-30 00:00:00'), Timestamp('2003-06-30 00:00:00')],
 10178: [Timestamp('1987-04-30 00:00:00'), Timestamp('1999-01-31 00:00:00')],
 10179: [Timestamp('1987-04-30 00:00:00'), Timestamp('1997-09-30 00:00:00')],
 10180: [Timestamp('1989-04-30 00:00:00'), Timestamp('2018-06-30 00:00:00')],
 10181: [Timestamp('1987-04-30 00:00:00'), Timestamp('1990-02-28 00:00:00')],
 10182: [Timestamp('1987-04-30 00:00:00'), Timestamp('2018-06-30 00:00:00')],
 10183: [Timestamp('1989-02-28 00:00:00'), Timestamp('2018-06-30 00:00:00')],
 10184: [Timestamp('1989-02-28 00:00:00'), Timestamp('1992-03-31 00:00:00')],
 10185: [Timestamp('1987-04-30 00:00:00'), Timestamp('1999-10-31 00:00:00')],
 10186: [Timestamp('1987-04-30 00:00:00'), Timestamp('1990-03-31 00:00:00')],
 10187: [Timestamp('1987-04-30 00:00:00'), Timestamp('1998-02-28 00:00:00')],
 10188: [Timestamp('1964-07-31 00:00:00'), Timestamp('1978-06-30 00:00:00')],
 10189: [Timestamp('1973-12-31 00:00:00'), Timestamp('1988-01-31 00:00:00')],
 10190: [Timestamp('1987-04-30 00:00:00'), Timestamp('1991-12-31 00:00:00')],
 10191: [Timestamp('1987-04-30 00:00:00'), Timestamp('1990-02-28 00:00:00')],
 10192: [Timestamp('1987-04-30 00:00:00'), Timestamp('2001-06-30 00:00:00')],
 10193: [Timestamp('1987-04-30 00:00:00'), Timestamp('1994-07-31 00:00:00')],
 10194: [Timestamp('1987-04-30 00:00:00'), Timestamp('2000-09-30 00:00:00')],
 10195: [Timestamp('1987-04-30 00:00:00'), Timestamp('2003-08-31 00:00:00')],
 10196: [Timestamp('1964-07-31 00:00:00'), Timestamp('1967-12-31 00:00:00')],
 10197: [Timestamp('1987-04-30 00:00:00'), Timestamp('1967-12-31 00:00:00')],
 10198: [Timestamp('1987-04-30 00:00:00'), Timestamp('1991-09-30 00:00:00')],
 10199: [Timestamp('1987-04-30 00:00:00'), Timestamp('1998-03-31 00:00:00')],
 10200: [Timestamp('1987-04-30 00:00:00'), Timestamp('2018-06-30 00:00:00')],
 10201: [Timestamp('2011-07-31 00:00:00'), Timestamp('2018-06-30 00:00:00')],
 10202: [Timestamp('1987-04-30 00:00:00'), Timestamp('1988-07-31 00:00:00')],
 10203: [Timestamp('1987-04-30 00:00:00'), Timestamp('1993-08-31 00:00:00')],
 10204: [Timestamp('1987-05-31 00:00:00'), Timestamp('1993-08-31 00:00:00')],
 10205: [Timestamp('1987-05-31 00:00:00'), Timestamp('2010-11-30 00:00:00')],
 10206: [Timestamp('1987-05-31 00:00:00'), Timestamp('1990-04-30 00:00:00')],
 10207: [Timestamp('1989-06-30 00:00:00'), Timestamp('2018-06-30 00:00:00')],
 10208: [Timestamp('1987-05-31 00:00:00'), Timestamp('1992-04-30 00:00:00')],
 10209: [Timestamp('1987-05-31 00:00:00'), Timestamp('1992-04-30 00:00:00')],
 10210: [Timestamp('1987-05-31 00:00:00'), Timestamp('1991-10-31 00:00:00')],
 10211: [Timestamp('1987-05-31 00:00:00'), Timestamp('2006-02-28 00:00:00')],
 10212: [Timestamp('1987-05-31 00:00:00'), Timestamp('1996-05-31 00:00:00')],
 10213: [Timestamp('1987-05-31 00:00:00'), Timestamp('1996-11-30 00:00:00')],
 10214: [Timestamp('1987-05-31 00:00:00'), Timestamp('1997-12-31 00:00:00')],
 10215: [Timestamp('1987-05-31 00:00:00'), Timestamp('1987-07-31 00:00:00')],
 10216: [Timestamp('1987-05-31 00:00:00'), Timestamp('2001-04-30 00:00:00')],
 10217: [Timestamp('1964-07-31 00:00:00'), Timestamp('1969-12-31 00:00:00')],
 10218: [Timestamp('1981-10-31 00:00:00'), Timestamp('1999-02-28 00:00:00')],
 10219: [Timestamp('2011-08-31 00:00:00'), Timestamp('1999-02-28 00:00:00')],
 10220: [Timestamp('2011-08-31 00:00:00'), Timestamp('2018-06-30 00:00:00')],
 10221: [Timestamp('1987-05-31 00:00:00'), Timestamp('1988-05-31 00:00:00')],
 10222: [Timestamp('1987-05-31 00:00:00'), Timestamp('1996-01-31 00:00:00')],
 10223: [Timestamp('2011-07-31 00:00:00'), Timestamp('2014-02-28 00:00:00')],
 10224: [Timestamp('1987-05-31 00:00:00'), Timestamp('1993-04-30 00:00:00')],
 10225: [Timestamp('1964-07-31 00:00:00'), Timestamp('2014-04-30 00:00:00')],
 10226: [Timestamp('1987-05-31 00:00:00'), Timestamp('2014-04-30 00:00:00')],
 10227: [Timestamp('1987-05-31 00:00:00'), Timestamp('1988-10-31 00:00:00')],
 10228: [Timestamp('1987-05-31 00:00:00'), Timestamp('1990-05-31 00:00:00')],
 10229: [Timestamp('1987-05-31 00:00:00'), Timestamp('1988-02-29 00:00:00')],
 10230: [Timestamp('1987-05-31 00:00:00'), Timestamp('2001-10-31 00:00:00')],
 10231: [Timestamp('1987-05-31 00:00:00'), Timestamp('1997-08-31 00:00:00')],
 10232: [Timestamp('1987-05-31 00:00:00'), Timestamp('2018-06-30 00:00:00')],
 10233: [Timestamp('1964-06-30 00:00:00'), Timestamp('1985-12-31 00:00:00')],
 10234: [Timestamp('1973-12-31 00:00:00'), Timestamp('1983-06-30 00:00:00')],
 10235: [Timestamp('1987-05-31 00:00:00'), Timestamp('2001-07-31 00:00:00')],
 10236: [Timestamp('1987-05-31 00:00:00'), Timestamp('1990-09-30 00:00:00')],
 10237: [Timestamp('1987-05-31 00:00:00'), Timestamp('1988-08-31 00:00:00')],
 10238: [Timestamp('1987-05-31 00:00:00'), Timestamp('2008-01-31 00:00:00')],
 10239: [Timestamp('1987-05-31 00:00:00'), Timestamp('2018-06-30 00:00:00')],
 10240: [Timestamp('1987-05-31 00:00:00'), Timestamp('1988-04-30 00:00:00')],
 10241: [Timestamp('1964-07-31 00:00:00'), Timestamp('1988-11-30 00:00:00')],
 10242: [Timestamp('1987-05-31 00:00:00'), Timestamp('1998-07-31 00:00:00')],
 10243: [Timestamp('1987-05-31 00:00:00'), Timestamp('1995-03-31 00:00:00')],
 10244: [Timestamp('1987-05-31 00:00:00'), Timestamp('2002-05-31 00:00:00')],
 10245: [Timestamp('1987-05-31 00:00:00'), Timestamp('1992-10-31 00:00:00')],
 10246: [Timestamp('1987-05-31 00:00:00'), Timestamp('1996-02-29 00:00:00')],
 10247: [Timestamp('1987-05-31 00:00:00'), Timestamp('1999-11-30 00:00:00')],
 10248: [Timestamp('1987-05-31 00:00:00'), Timestamp('1996-01-31 00:00:00')],
 10249: [Timestamp('1987-05-31 00:00:00'), Timestamp('1988-09-30 00:00:00')],
 10250: [Timestamp('1987-05-31 00:00:00'), Timestamp('1997-11-30 00:00:00')],
 10251: [Timestamp('1987-05-31 00:00:00'), Timestamp('1992-10-31 00:00:00')],
 10252: [Timestamp('1987-05-31 00:00:00'), Timestamp('2018-06-30 00:00:00')],
 10253: [Timestamp('2004-04-30 00:00:00'), Timestamp('2018-06-30 00:00:00')],
 10254: [Timestamp('1987-05-31 00:00:00'), Timestamp('1987-07-31 00:00:00')],
 10255: [Timestamp('1987-05-31 00:00:00'), Timestamp('1988-08-31 00:00:00')],
 10256: [Timestamp('1987-05-31 00:00:00'), Timestamp('2001-06-30 00:00:00')],
 10257: [Timestamp('1987-05-31 00:00:00'), Timestamp('2018-06-30 00:00:00')],
 10258: [Timestamp('1987-05-31 00:00:00'), Timestamp('2018-06-30 00:00:00')],
 10259: [Timestamp('1987-05-31 00:00:00'), Timestamp('2018-06-30 00:00:00')],
 10260: [Timestamp('1987-05-31 00:00:00'), Timestamp('1990-07-31 00:00:00')],
 10261: [Timestamp('1987-04-30 00:00:00'), Timestamp('1993-12-31 00:00:00')],
 10262: [Timestamp('1987-05-31 00:00:00'), Timestamp('1990-11-30 00:00:00')],

In [37]:
start_time = time.time()
stock_components = {}

# find_stocks will save the tickers of the stocks available at given date and return a list of them
def find_stocks(target_date):
    stock_lst = []
    for ticker in dates:
        if dates[ticker][0] <= target_date and dates[ticker][1] >= target_date:
            stock_lst.append(ticker)
    return stock_lst


for i in dates_month:
    stock_components.update({i:find_stocks(i)})
    
print(time.time()-start_time)

22.41545009613037

In [39]:
# Find the components of the portfolio for a given date 
def find_component(date,
                  start_time):
    date_df = []
    for stock in stock_components[date]:
        data_slice = pd.DataFrame(data[dates_ind[stock][0]:dates_ind[stock][1]+1])
        n = np.where(data_slice['date']==date)
        date_df.append(data_slice.iloc[n])
    print(time.time()-start_time)
    return pd.concat(date_df)

frame = find_component(datetime.datetime(2018, 6, 30, 0, 0), time.time())

8.577442646026611

         PERMNO       date   DIVAMT        PRC     SHROUT  Rolling 12m Vol
3747      10026 2018-06-30  0.45000  152.47000    18697.0         7.317630
4188      10028 2018-06-30  0.00000    0.72000    26924.0         0.303481
4771      10032 2018-06-30  0.00000   59.54000    32361.0         3.499549
6520      10044 2018-06-30  0.12000   11.44000     5905.0         0.325293
9865      10065 2018-06-30  0.00000   15.42000   101627.0         0.340294
14693     10104 2018-06-30  0.00000   44.06000  3981155.0         1.980292
15211     10107 2018-06-30  0.00000   98.61000  7677000.0         9.610294
15634     10113 2018-06-30  0.28385   53.24000     4625.0         4.372658
19278     10138 2018-06-30  0.70000  116.09000   243180.0        14.050995
20733     10145 2018-06-30  0.00000  144.05000   746930.0         7.715157
22870     10158 2018-06-30  0.00000   12.00000    29566.0         1.998485
25757     10180 2018-06-30  0.00000   16.59000   125404.0         8.026923
26194     10182 2018-06-30  0.00000   82.12000    38322.0         9.092902
28442     10200 2018-06-30  0.00000   47.04000    43799.0         3.106011
28539     10201 2018-06-30  0.00000    2.20000   112464.0         0.166875
29387     10207 2018-06-30  0.12900    7.82000    24875.0         0.214338
30781     10220 2018-06-30  0.00000   62.32000    99680.0         5.548390
32525     10232 2018-06-30  0.05750   20.42500     3499.0         0.203187
32526     10232 2018-06-30  0.24150   20.42500     3499.0         0.201273
33864     10239 2018-06-30  0.00000   24.40000    12380.0         0.800477
35778     10252 2018-06-30  0.38000   78.40000    27533.0         2.808132
36165     10253 2018-06-30  0.00000    1.28000    16599.0         0.364274
36783     10257 2018-06-30  0.00000    5.48000    11899.0         0.299930
37170     10258 2018-06-30  0.00000    0.50360   156646.0         0.749872
37557     10259 2018-06-30  0.00000    6.10000    39990.0         0.326280
41072     10294 2018-06-30  0.00000   22.00000     1767.0         2.165517
42544     10302 2018-06-30  0.11000   15.58000   359920.0         1.292462
43608     10308 2018-06-30  0.00000   85.88000    15286.0         4.342713
44521     10318 2018-06-30  0.00000   98.14000    32209.0         5.948260
46394     10333 2018-06-30  0.00000   20.88000     8379.0         9.008620
...         ...        ...      ...        ...        ...              ...
4093336   93372 2018-06-30  0.26500   48.00000    22701.0         4.327165
4093435   93373 2018-06-30  0.00000    9.15000    74524.0         1.245849
4093533   93374 2018-06-30  0.38000   51.72000   111545.0         4.392335
4093655   93376 2018-06-30  0.23247   56.41000     2900.0         2.087133
4093755   93377 2018-06-30  0.44642   22.97000    14750.0         1.205051
4093854   93378 2018-06-30  0.43927   47.33000     1400.0         1.718163
4093953   93379 2018-06-30  0.01782   21.78000    11550.0         1.642358
4094052   93380 2018-06-30  0.00000   13.77000    86928.0         3.735586
4094332   93384 2018-06-30  0.00000    2.09000    38507.0         2.641855
4094441   93385 2018-06-30  0.01923   33.82000     6800.0         0.685516
4094922   93393 2018-06-30  0.00000    6.38000    55753.0         2.715382
4095045   93396 2018-06-30  0.00000    7.63000      714.0         1.247003
4095144   93397 2018-06-30  0.00000   24.61000    17260.0         1.060405
4095307   93399 2018-06-30  0.00000    0.94890    24344.0         0.502999
4095483   93401 2018-06-30  0.00000    5.60000    44871.0         0.894311
4095672   93406 2018-06-30  0.00000    1.22000     5725.0         0.086634
4096324   93415 2018-06-30  0.00000   14.13000    70249.0         1.176233
4096422   93416 2018-06-30  0.16000    9.15000     9732.0         0.849623
4096687   93419 2018-06-30  0.25000   35.43000   156680.0         1.208590
4096785   93420 2018-06-30  0.00000   12.97000   317308.0         1.576136
4096883   93421 2018-06-30  0.03565   26.14000     5100.0         0.551702
4096980   93422 2018-06-30  0.00000   12.26000   237708.0         1.320003
4097078   93423 2018-06-30  0.00000   70.05000    83544.0         3.687336
4097176   93424 2018-06-30  0.00000   16.44000     4450.0         0.677705
4097274   93425 2018-06-30  0.00000   22.18000     4750.0         2.627598
4097371   93426 2018-06-30  0.00000   38.15000    12429.0         5.447948
4097469   93427 2018-06-30  0.00000   36.89000    36902.0         5.857682
4097661   93429 2018-06-30  0.00000  104.07000   112107.0        12.440925
4097922   93434 2018-06-30  0.00000    3.25000    25991.0         0.335074
4098045   93436 2018-06-30  0.00000  342.95001   170516.0        29.209012

[6717 rows x 6 columns]

In [ ]:
# Pick low-vol decile